// src/tmdb/seeds.jsTV
export const seeds = [
    // TV
    {
        title: '연인',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 206693,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/206693_bg.png',
        titleLogo: '/images/ott/detail/206693_logo.png',
        genre_ids: [14, 18],
    },
    {
        title: '옷소매 붉은 끝동',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 132925,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/132925_bg.png',
        titleLogo: '/images/ott/detail/132925_logo.png',
    },
    {
        title: '연모',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 129478,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/129478_bg.png',
        titleLogo: '/images/ott/detail/129478_logo.png',
    },
    {
        title: '백일의 낭군님',
        type: 'tv',
        year: 2018,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 81821,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/81821_bg.png',
        titleLogo: '/images/ott/detail/81821_logo.png',
    },
    {
        title: '구르미 그린 달빛',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66256,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/66256_bg.png',
        titleLogo: '/images/ott/detail/66256_logo.png',
    },

    {
        title: '신입사관 구해령',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 90721,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/90721_bg.png',
        titleLogo: '/images/ott/detail/90721_logo.png',
    },
    {
        title: '옥씨부인전',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 226649,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/226649_bg.png',
        titleLogo: '/images/ott/detail/226649_logo.png',
    },
    {
        title: '혼례대첩',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 230024,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/230024_bg.png',
        titleLogo: '/images/ott/detail/230024_logo.png',
    },
    {
        title: '킹덤',
        type: 'ott',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 70593,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop: '/images/ott/detail/70593_bg.png',
        titleLogo: '/images/ott/detail/70593_logo.png',
    },
    {
        title: '조선로코 - 녹두전',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 93541,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/93541_bg.png',
        titleLogo: '/images/ott/detail/93541_logo.png',
    },
    {
        title: '폭군의 셰프',
        type: 'tv',
        year: 2025,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 280945,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop: '/images/ott/detail/280945_bg.png',
        titleLogo: '/images/ott/detail/280945_logo.png',
    },

    {
        title: '고려 거란 전쟁',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 218290,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: '/images/ott/detail/218290_bg.png',
        titleLogo: '/images/ott/detail/218290_logo.png',
    },
    {
        title: '화랑',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66496,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/K02_T2016-0151-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/K02_T2016-0151-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '궁',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 5279,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/8azpI0t_S-hs_PZ3zLwuWw/1680x945sr.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/meta/image/202409/1725366929550193837.png',
    },

    {
        title: '환혼',
        type: 'tv',
        year: 2022,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 135157,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop: '/images/ott/detail/135157_bg.png',
        titleLogo: '/images/ott/detail/135157_logo.png',
    },
    {
        title: '철인왕후',
        type: 'tv',
        year: 2020,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 108261,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABeTwzdlIv_3ED-fIp1bX3hZv1qz614Rj2XjE5vPztNEYZobjf2y2E06DPQrVm3D8iE_G78pn4GrRp53RyTZJPtnzEcvwZ0XeaoIG.webp?r=9a3',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABedeIb6b43il0NU7MZuYTUx1tSRVpyEJbAviau_ayheKXGOgG9E9ZQR0o9NyYGuipWXtlPxsVmvheGPr7xUABQH6qMX5jgS1Dw.webp?r=495',
    },
    {
        title: '달의 연인 - 보보경심 려',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        aka: ['달빛연인'],
        tmdbId: 66433,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABVyS3aovwEcauCzSt440xHNz-sHf837gTJefd9kTjAecStZZgN1pjiHt3fwK_s0sRvzZD8juDsBB5T8t1VdBEFLyISC-8kJ0-YMJ.webp?r=217',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABZKRhL7xHrgdhHTU1zquepkMHJ4pAC6G7emBcmDQjuGvWRExO5YKQUPc3BXdIKrWSg4iXxWpCISjlQGVnnT5cvqNVU8GZuGuZg.webp?r=016',
    },
    {
        title: '퐁당퐁당 LOVE',
        type: 'tv',
        year: 2015,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 65355,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/ay2quyev6vlmEEX7Qbfdbw/1680x945sr.webp',
        titleLogo:
            'https://an2-img.amz.wtchn.net/image/v2/zr3weFnbPZ60OLLp4Es9Qg.png?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKd0lqb2lMM1l5TDNOMGIzSmxMMmx0WVdkbEx6RTJNemswTmpRNE16Y3lOamczTkRBM09EWWlMQ0pvSWpveE1qQjkuc1NTUEdqM3lnbjNZZ3d0WjFUTXZ4V2JaYmVTSG9ielVBSlUyM084cVl2RQ==',
    },
    {
        title: '옥탑방 왕세자',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 43152,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABcH6wS-azp5Ga5K4IviAtaWl-3RkQzh0xgdonKDC-9kOygmX3pvtNpWKabbGBlTjd0UGYTWbWuZl8ABBZHgiYFVQywlqqtZjcDCq.webp?r=47b',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABXWF4CFATvqbrN52llwUeB4FG870qVqtSlNY24xl6LFS0sWYc3vAwc2hbFGL2bZ_RT3pMyW_ug10kG-6cmG0FRu2xMKxnAxThg.webp?r=5db',
    },

    {
        title: '낮에 뜨는 달',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 230924,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABZqrXboAqRRcCfNldrc5swwIj4wOahTPqEpkK_Qd6hCVDxYfbofNjye1w_-_CInQONl7lEjxHxhSOogF61Jxjegxa8zBqWatecBp.webp?r=aa5',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABU649TqVF_8ty9D-pi_Npd0pmisYmveLc5WxREM1q_b9uUzhF9nj9wbqjXm_lOfzrsc3611xkXhDjS-EhNlyeqVbBlhBkES8sw.webp?r=7b5',
    },
    {
        title: '귀궁',
        type: 'tv',
        year: 2025,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 259486,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/meta/image/202504/1744941555399831650.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/meta/image/202504/1744941572476533098.png',
    },
    {
        title: '청춘월담',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 154889,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABR3CMIFZoGwCrDD4CFmrPps67Czyv18H2i2F7tlLWr0L4GJaok6fVMIefANWjHqoTJmVPNinZ9BUFNgmToexvSAoZDCF7ckmaCmZ.webp?r=6ab',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABa6qQTyzRgTaZaKWeZNCRQiHuZ09utQnFu_kXe7fjCEEEwp87vbUXs3fTYXKfAp4oeP2NpJY4_QLa7Ijp_gA5hERdQnxA6JBlQ.webp?r=4fb',
    },
    {
        title: '열녀박씨 계약결혼뎐',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 220076,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop:
            'https://img.coupangstreaming.com/titles/428d9891-811b-430c-bfd3-8d248ceb4481/hero-largescreen/4461d07a-bef0-45b0-81e1-db0503de2e70.jpg?imwidth=1280&imscalingMode=aspectFit&quot',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/meta/image/202311/1700806949866978669.png',
    },
    {
        title: '인현왕후의 남자',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 44964,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/BfLfXu3jbsgXYlzOt3yVfA/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/KhXAFPXjg_9EPaGLF-RoeQ/760x286.png',
    },

    {
        title: '장영실',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 64811,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/DR-IPyp2avVFbdmn5VyxKw/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/olGpk_qt17niWr8v5Y29bg/760x286.png',
    },
    {
        title: '태종 이방원',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 135751,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: '/images/ott/detail/135751_bg.png',
        titleLogo: '/images/ott/detail/135751_logo.png',
    },
    {
        title: '불멸의 이순신',
        type: 'tv',
        year: 2004,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 14534,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/K01_T2004-0084-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/K01_T2004-0084-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '태조 왕건',
        type: 'tv',
        year: 2000,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 17039,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://an2-img.amz.wtchn.net/image/v2/bafIf1lSoViuMSCymNPE6g.webp?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5qUXdlRE0yTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk1UQTFNekUwTlRNek1qYzRNamMzTVRBaWZRLk80SDF4ekw1WTFFVHJNX0NOX0IzTGdFUWZpenZaaFRVN2Z6aUdtVVJJTE0=',
        titleLogo:
            'https://i.namu.wiki/i/dl5dP5YkaF0NkICeIf65P1UVeyH5-biI71HnEV6-lvgr8BwM4LncTQltyxyfL9u_BkOUvVYGhdm8fHwpw6NxVg.webp',
    },
    {
        title: '동이',
        type: 'tv',
        year: 2010,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 38852,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/efml5ayFoHTkmLaTmTdpHg/1680x945.webp',
        titleLogo:
            'https://an2-img.amz.wtchn.net/image/v2/dNBUAcuK1xgMMu0_GxEBOg.png?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKd0lqb2lMM1l5TDNOMGIzSmxMMmx0WVdkbEx6RTJNemsyTkRFd056UTFOVGM1TlRjM05ESWlMQ0pvSWpveE1qQjkuck13UThna0otUkxhMzhIS3d6UVJFRG4tc2pVMUlMdjltWG1xSjhHQnYwWQ==',
    },
    {
        title: '선덕여왕',
        type: 'tv',
        year: 2009,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 21771,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/r7DW7sf14gp9y33WLNu-xA/1680x945.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/bVyRzIsISzXkF2rXIBhAJQ/760x286.png',
    },
    {
        title: '정도전',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66580,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/K01_T2013-0183-Horizontal_LogoN.webp',
        titleLogo: 'https://www.wavve.com/player/vod?programid=K01_T2013-0183&autoplay=y',
    },
    {
        title: '연개소문',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 3852,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABUEOq958FIIp5HCSlugv9GIRyYT8Ct0FiEyegay59oZ8C7_ndm5nMVUVP3p4AnJL6rKUL_y6OTVjw4kwegAOL3OgmkqSgj11QqqA.webp?r=c69',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABZYOD352KTp0TwTpv54v8n9tYCnWEugWRfz_DaQ1Preko5yDON2jNYASxl4nG9OXRtI0bCqyq2K4f3bUZFcxvom1o8ltmTGslg.webp?r=7b9',
    },
    {
        title: '광개토태왕',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 39606,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://gimgcache.uplus.co.kr/still/ST_M01124UA06PPV00_105206.jpg',
        titleLogo:
            'https://i.namu.wiki/i/4QTmLDz7q1dTc1LJvExUyhtmPkkf49QZWIiLv1G-XE3dZlN-Rg_JG7k3m-4C5u8MaZR9aMFbR5wazh5VRAfHtQ.webp',
    },
    {
        title: '대왕세종',
        type: 'tv',
        year: 2008,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 14085,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/K02_T2007-0415-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/K02_T2007-0415-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '대장금',
        type: 'tv',
        year: 2003,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 333,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2022/M_T66244G-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2022/M_T66244G-SingleColorContentLogo-Trimmed.png',
    },
    {
        title: '주몽',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 4734,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/WoFdEPChwTtUtW0b8W1vTw/1680x945.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/mPqyJV4V6vQD6M0WpKrdWg/760x286.png',
    },
    {
        title: '여인천하',
        type: 'tv',
        year: 2001,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 24165,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABWZSkvSa5x7fTv7Z1KW9YBOzsL8ODivJ0PlDBg7Klj7_othZ6QUq2brTYDKsxic__dKAH5pK37q-5ialHvcjXcTl2YNOYoCf11-z.webp?r=07e',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABRNWDrWParqJFUrR-oMt7Hhgk57LH6e53hqzGS_zCMvKjOTsNKZvgfwqsItFoIlEhuaPiA_wCUt1etVLsy2DH9yK9yphsjWirg.webp?r=1d2',
    },
    {
        title: '이산',
        type: 'tv',
        year: 2007,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 15135,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/tpiA7XLkL1qpyyHmlnyhMw/1680x945.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/3q5IYmFjlp1CMN5bAUhdow/760x286.png',
    },
    {
        title: '해치',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 86094,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABTsVgAw2SBfYvdM0fr6rHcWJ0y28_ZhVl9AxzuTHl3HjOUJyZB3Ukyt29oVoA3BA-HvE5dBpqwjowL_PQqFTCkrGtypMiUBAWzyW.webp?r=e95',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABYVnF81gqBxdAlZD8U_U6uHJ5zUfOU--IkM8WDxvkEj4Pbmdm5tv5w-RKWva4LTP3JbgUFU8L7YmGFIFFFKLP7NQXnCFgI72inc.webp?r=632',
    },
    {
        title: '비밀의 문',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61488,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/dFMc8vq-4F3i8gBV6U5jjg/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/re-segOR2LrlZjclLOElAQ/760x286.png',
    },
    {
        title: '역적 : 백성을 훔친 도적',
        type: 'tv',
        year: 2017,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 68892,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://an2-img.amz.wtchn.net/image/v2/TxZfZHcJaaLVtjkyTM2rAw.webp?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk1USTRNSGczTWpCeE9EQWlYU3dpY0NJNklpOTJNaTl6ZEc5eVpTOXBiV0ZuWlM4Mk5qVXhNakUyTWpJeE1UUTBNVFVpZlEuNTFmSnpOcnBRN21DSmU1MVVOM3hsN0VXcTFfUi1OOFAtT1p3bHRUeEpodw==',
        titleLogo:
            'https://an2-img.amz.wtchn.net/image/v2/9TyN2ozVbs2krwpSZY5jZg.png?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKd0lqb2lMM1l5TDNOMGIzSmxMMmx0WVdkbEx6RTJORFF4T1RnM05qRTVOREU1TlRVd09UZ2lMQ0pvSWpveE1qQjkuMjFRVW9Yd1FVbnNjYkpPZEVFX1dfRVF5OHhOY1ZyNzVnbDF0UHFDdjRQVQ==',
    },
    {
        title: '왕과 나',
        type: 'tv',
        year: 2007,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 15961,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABWK7Mi-GGpRJqLXJgIRKGhNP2IC0CDUx6m60M9MczM8lKyGtN6E5LVOEcPFohWslBr16Pl6MwaukbTwqRFewQH4Gidn_kNw8vEzI.webp?r=7c4',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABb1sUEE7y5AbBbJloXilPaMjE2x3eEJH7Ww2p1jIMPNzF1hXuemgvm-IZX2QeGeMhhqppDkqiUkNFYNw-paS5J1ybHHbz9od8w.webp?r=034',
    },
    {
        title: '장희빈',
        type: 'tv',
        year: 2002,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 70397,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/Z_wHRuOZzLmwCtYnMtnLww/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/tbxDflGBwNSGh2hILxYvTw/760x286.png',
    },
    {
        title: '근초고왕',
        type: 'tv',
        year: 2010,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 35278,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/K01_AG2020-0005-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/K01_AG2020-0005-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '무신',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 46573,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/M_T60154G-Horizontal_LogoN.webp',
        titleLogo:
            'https://i.namu.wiki/i/P6uP7J69FkiS_KyAzccu2UNQal8JFWokuN35TCHSpMS-tULOF2mswGIID4WJvN7A-QjsQ_PngSSXqyoWAuGFww.webp',
    },
    {
        title: '마의',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 45049,
        mediaType: 'tv',
        genre: 'orthodox',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/M_T60173G-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/M_T60173G-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '황진이',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 565304,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABXl2IYGvOvlLz4rOPDOtD1o7Njw3hW8HOa5l_8ttfX_IGMjGfLSU4gJutv-6MBZiK6fUso3X5lflsIzyPS2OWBAmbm3wPB5eK00q.webp?r=cdd',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABVRTr35HqcxhEsZGvcdjcBENEeJ2qy1CxwOeHY8lxH2wyt-38FzL6hZmfHVWxSHJIAZcEM9xQWv4qDuEcnFrD4jqBHIk3n-2Ew.webp?r=8c5',
    },
    {
        title: '육룡이 나르샤',
        type: 'tv',
        year: 2015,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 63927,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2022/S01_V2000008547-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2022/S01_V2000008547-SingleColorContentLogo-Trimmed.png',
    },
    {
        title: '해를 품은 달',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 45579,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/M_T60156G-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/M_T60156G-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '뿌리 깊은 나무',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 41652,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2022/S01_V0000352936-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2022/S01_V0000352936-SingleColorContentLogo-Trimmed.png',
    },
    {
        title: '추노',
        type: 'tv',
        year: 2010,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 31424,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/BMS/TVSeason/2023/K02_T2009-0897-Horizontal_LogoN.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/K02_T2009-0897-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '일지매',
        type: 'tv',
        year: 2008,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 21013,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABcbpdb9v5nrItA4ISbzXarA-gCN1vso-6UbwZQ5QlXffHB2SDs_qU19aPYZFaObo0B8GZXlDWqpg5_lJ3d82SErqOg9KHwm8v6n-.webp?r=c39',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABbL-UiITWk1R0BCD6A_W1pWV1zGI1WHqyL3PzxF5VYk82QwpNKDj1VCSj-pSvkInVYASgdN2k33jWLqpfHZp8lUjlU4uwmsR6Rk.webp?r=47d',
    },
    {
        title: '슈룹',
        type: 'tv',
        year: 2022,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 156406,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/156406_bg.png',
        titleLogo: '/images/ott/detail/156406_logo.png',
    },
    {
        title: '기황후',
        type: 'tv',
        year: 2013,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61148,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABW7iTVLe8KAFj8HY5UpcLY7GIDw-YthRmFxlhbDq9VICeOrVCUUX0IxFpXlVPeEi5U0JSWtaI54WQ-BKc1fHFFsd18yt3nckOo0Z.webp?r=f4a',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABae6hw_CFLGLooSAU9QphA7f9NPa3mLZzyEzjCC6lhYPGpAvej1d7751wjNYyo-MwQQYlpRNO3Svmm9fUC_GwzLeZ9OoYK_gjQ.webp?r=ada',
    },
    {
        title: '달이 뜨는 강',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 116605,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/Z9GestZZ4xld31B1lvznxg/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/IfZDbZHhaThAFPDCPIGwWA/760x286.png',
    },
    {
        title: '군주 - 가면의 주인',
        type: 'tv',
        year: 2017,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 69975,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://an2-img.amz.wtchn.net/image/v2/J40qIgQ4SXattKCFIgzQ5Q.webp?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk1USTRNSGczTWpCeE9EQWlYU3dpY0NJNklpOTJNaTl6ZEc5eVpTOXBiV0ZuWlM4eE5qRTFPRGN5TnpJM05qWXhNVFl4TmpRMUluMC4tNFJsZXlvdktfYVFTUUJCM19XZEMzRy1vVFlEVEh6LXNKdWRoS1luYnJN',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/QhsFYc5RPDppsEcikUlCKg/760x286.png',
    },
    {
        title: '7일의 왕비',
        type: 'tv',
        year: 2017,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 71748,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/lyJ0VZXVBDAnfhbobACRGg/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/9oh61oW9eMk6RQO-QApRrA/760x286.png',
    },
    {
        title: '나의 나라',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 93490,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABdwSCdQWgihHJUg8MYF48UcDWcnQH2MnG5hrESXIos7LnPwrqJ9ymBIfj6mcFnXLj_440ayvRsjmXUHj2lvkdihk1CB4L22R7vWu.webp?r=b67',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABQDuZVyvh66ErBLiovRVaUGAkUPpnkNc_FQHo4aT87hMjs-2OjdkQ3zueSEFqDb7Ei_MflDlbVHUA3ueXctEah9d3JMTDCNrhg.webp?r=5a4',
    },
    {
        title: '세작, 매혹된 자들',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 233205,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABcmjJVxpxlflsDhLe5YY3Cxr2STPAycWXfnzcpedBCYOE_O9Is9ydO0N2qGpZiR9X0T3R8RF4JmvCrgkh5mLsJkXDfL2Kw-yX2U3.webp?r=665',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABVkbdVyouUk74U3kql1bbqzJpe7ZgFNMyu_V9vh0lK3hb68jU7xNUcspYBsDg-gXQaKbRfx7TPmjJ4gvivc7cW91oYuuzkZo6A.webp?r=a26',
    },
    {
        title: '왕의 얼굴',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61830,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/R1dQPp8ria5CTb445a7KNA/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/F-yOYMYmLVyOGQfKpyuh2Q/760x286.png',
    },
    {
        title: '조선총잡이',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61184,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/WcPMehSe2lOP-ZKbg2V3_g/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/F48O18YqHAFPub8gRyTomw/760x286.png',
    },
    {
        title: '세자가 사라졌다',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 235576,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/AQKGkapNePHVDREIkTXl9Q/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/ZcN6VdM3nvpiv71i7frIaQ/760x286.png',
    },
    {
        title: '장옥정, 사랑에 살다',
        type: 'tv',
        year: 2013,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 47322,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABROrbu2HTdoOuVDvoVMODeHBEjlilPjpknZ29MwaCr7a3n-YTdpxjGA4EDAiUUxPLRiL9xpiTEXVTN6oM097NMm6-Ytj82xZYVL9.webp?r=49b',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABabb0TeztzlhU2ODULVzgpf8kX-iCsOiuU1xREehnAdveLh332qmit_wHbyI50-QlN8qNhyDn9657Fqjfphy7o26XoQeqjwkxfI.webp?r=f45',
    },
    {
        title: '우씨왕후',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 224732,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://mimgnews.pstatic.net/image/upload/component/2024/08/26/161258110_Ncontents_image.jpg?type=w800',
        titleLogo:
            'https://image.tving.com/ntgs/contents/CTC/caip/CAIP1800/ko/20240730/0651/P001759741.png/dims/resize/F_webp,800?from=pc',
    },
    {
        title: '공주의 남자',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 40239,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://an2-img.amz.wtchn.net/image/v2/jxswiaL-3w6dm9Dxwx3AeA.webp?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk1USTRNSGczTWpCeE9EQWlYU3dpY0NJNklpOTJNaTl6ZEc5eVpTOXBiV0ZuWlM4eE5qRTFPRFkzTkRVNE1ESTJNalEyTVRFekluMC5xOUE0M1ZHT2h0S042a0wwU0ZWbjQwOEdnZTRyM0hNNm9GdFZoME1oaFVZ',
        titleLogo:
            'https://an2-img.amz.wtchn.net/image/v2/lKjXg15_dvOdBfQ2cTc4DQ.png?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKd0lqb2lMM1l5TDNOMGIzSmxMMmx0WVdkbEx6RTJNemt6T0RjMk9UZzRNRGMzTXpneE5qQWlMQ0pvSWpveE1qQjkuTU5VU2RRWmpLNUZ3NVJXbGpMTzE0eFY1am9nU0NTMHpDOHl5MC1xTTh5dw==',
    },
    {
        title: '보쌈-운명을 훔치다',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 113623,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/AKflw_XES-j3Hpi1Kd4_Jg/1680x945.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/BMS/TVSeason/2023/C9901_C99000000056-SingleColorContentLogo_Trimmed.png',
    },
    {
        title: '대왕의 꿈',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66719,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/jgzZVkPqr0-gVerCun-akA/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/NkPo9a2xATcd6ldvLvYXLQ/760x286.png',
    },
    {
        title: '불의 여신 정이',
        type: 'tv',
        year: 2013,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 51866,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: 'https://is1-ssl.mzstatic.com/image/thumb/jZ8pFJOaem1CtN8ESwq55w/1680x945sr.webp',
        titleLogo: 'https://is1-ssl.mzstatic.com/image/thumb/lpkZpPSPtTrPvSET63f3pg/760x286.png',
    },
    {
        title: '무사 백동수',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 40016,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABST4asED277NL3Ax6d_XIlJ9zs7LazqMbN6S4U9yAKznKByHA8L53tP_ByU0O7D9rawrLGgHK82yP4LaqTJNLnT28wvIupDEFBpv.webp?r=8ac',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABZdoDUMIX_34kXFoFfMQMiTwIKDEW5S8AlRpDStQKxnjsu3_iPXi2mZZengPgK6zVgfPrh3r_WJJ4hgSoxQuuBiTcp5G3OFSRQ.webp?r=77fhttps://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABST4asED277NL3Ax6d_XIlJ9zs7LazqMbN6S4U9yAKznKByHA8L53tP_ByU0O7D9rawrLGgHK82yP4LaqTJNLnT28wvIupDEFBpv.webp?r=8ac',
    },
    {
        title: '원경',
        type: 'tv',
        year: 2025,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 226103,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/detail/226103_bg.png',
        titleLogo: '/images/ott/detail/226103_logo.png',
    },

    // Movie
    {
        title: '사도',
        type: 'movie',
        year: 2015,
        tags: ['sageuk'],
        tmdbId: 315439,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/detail/315439_bg.png',
        titleLogo: '/images/ott/detail/315439_logo.png',
    },
    {
        title: '명량',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 282631,
        mediaType: 'movie',
        genre: 'action',
        backdrop: '/images/ott/detail/282631_bg.png',
        titleLogo: '/images/ott/detail/282631_logo.png',
    },
    {
        title: '한산:용의 출현',
        type: 'movie',
        year: 2022,
        tags: ['sageuk'],
        tmdbId: 588108,
        mediaType: 'movie',
        genre: 'action',
        backdrop: '/images/ott/detail/588108_bg.png',
        titleLogo: '/images/ott/detail/588108_logo.png',
    },
    {
        title: '노량:죽음의 바다',
        type: 'movie',
        year: 2023,
        tags: ['sageuk'],
        tmdbId: 660360,
        mediaType: 'movie',
        genre: 'action',
        backdrop: '/images/ott/detail/660360_bg.png',
        titleLogo: '/images/ott/detail/660360_logo.png',
    },
    {
        title: '관상',
        type: 'movie',
        year: 2013,
        tags: ['sageuk'],
        tmdbId: 220176,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/detail/220176_bg.png',
        titleLogo: '/images/ott/detail/220176_logo.png',
    },
    {
        title: '왕의 남자',
        type: 'movie',
        year: 2005,
        tags: ['sageuk'],
        tmdbId: 45035,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/detail/45035_bg.png',
        titleLogo: '/images/ott/detail/45035_logo.png',
    },
    {
        title: '광해:왕이 된 남자',
        type: 'movie',
        year: 2012,
        tags: ['sageuk'],
        tmdbId: 133200,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/detail/133200_bg.png',
        titleLogo: '/images/ott/detail/133200_logo.png',
    },

    {
        title: '봉이 김선달',
        type: 'movie',
        year: 2016,
        tags: ['sageuk'],
        tmdbId: 385137,
        mediaType: 'movie',
        genre: 'comedy',
        backdrop: '/images/ott/detail/385137_bg.png',
        titleLogo: '/images/ott/detail/385137_logo.png',
    },
    {
        title: '조선마술사',
        type: 'movie',
        year: 2015,
        tags: ['sageuk'],
        tmdbId: 366654,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/detail/366654_bg.png',
        titleLogo: '/images/ott/detail/366654_logo.png',
    },
    {
        title: '명당',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 544089,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/detail/544089_bg.png',
        titleLogo: '/images/ott/detail/544089_logo.png',
    },
    {
        title: '조선명탐정:흡혈괴마의 비밀',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 334486,
        mediaType: 'movie',
        genre: 'comedy',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/movieImg/MovieGroup/2023/GMV_SB01_SB0000000049-Horizontal_LogoN-re.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/movieImg/MovieGroup/2023/GMV_SB01_SB0000000049-SingleColorContentLogo_Trimmed-re.png',
    },
    {
        title: '궁합',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 500168,
        mediaType: 'movie',
        genre: 'comedy',
        backdrop:
            'https://image.wavve.com/v1/thumbnails/1240_698_20_80/meta/image/202310/1697156091026344693.webp',
        titleLogo:
            'https://image.wavve.com/v1/thumbnails/0_0_20_80/meta/image/202310/1697156102679708447.png',
    },
    {
        title: '임금님의 사건수첩',
        type: 'movie',
        year: 2017,
        tags: ['sageuk'],
        tmdbId: 451914,
        mediaType: 'movie',
        genre: 'comedy',
        backdrop:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/Z-WHgqd_TeJxSuha8aZ5WpyLcX8/AAAABeQkY-VK0QFLov-Nb09VH_o4Z4zrRAZKJfGG5P9hr7laCL13DDl0jXYJfUg9qpUchdfSm9a0aXyobYhyyMXl5iGcC6ZESrKOO8ps.webp?r=fa9',
        titleLogo:
            'https://occ-0-4342-993.1.nflxso.net/dnm/api/v6/S4oi7EPZbv2UEPaukW54OORa0S8/AAAABTLRUs7NP1KShKdYrpjkqHVhvt0YXwgm33rufub2VKkxWH65RANM9Gui-ZZd9rq_weILsRtm_wLxJ_2K4a9yYPcadsByyOKBng.webp?r=6a3',
    },
    {
        title: '군도',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 281780,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '최종병기 활',
        type: 'movie',
        year: 2011,
        tags: ['sageuk'],
        tmdbId: 79224,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '황진이',
        type: 'movie',
        year: 2007,
        tags: ['sageuk'],
        tmdbId: 56247,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '바람과 함께 사라지다',
        type: 'movie',
        year: 2012,
        tags: ['sageuk'],
        tmdbId: 132711,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '나는 왕이로소이다',
        type: 'movie',
        year: 2012,
        tags: ['sageuk'],
        tmdbId: 138713,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '남한산성',
        type: 'movie',
        year: 2017,
        tags: ['sageuk'],
        tmdbId: 437081,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '나랏말싸미',
        type: 'movie',
        year: 2019,
        tags: ['sageuk'],
        tmdbId: 572988,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '전우치',
        type: 'movie',
        year: 2009,
        tags: ['sageuk'],
        tmdbId: 40171,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '불꽃처럼 나비처럼',
        type: 'movie',
        year: 2009,
        tags: ['sageuk'],
        tmdbId: 41441,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '신기전',
        type: 'movie',
        year: 2008,
        tags: ['sageuk'],
        tmdbId: 50341,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '올빼미',
        type: 'movie',
        year: 2022,
        tags: ['sageuk'],
        tmdbId: 806128,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '자산어보',
        type: 'movie',
        year: 2021,
        tags: ['sageuk'],
        tmdbId: 581390,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '천문: 하늘에 묻는다',
        type: 'movie',
        year: 2019,
        tags: ['sageuk'],
        tmdbId: 569267,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '해적: 바다로 간 산적',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 285213,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '역린',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 269340,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '상의원',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 314327,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '전,란',
        type: 'movie',
        year: 2024,
        tags: ['sageuk'],
        tmdbId: 1075676,
        mediaType: 'movie',
        genre: 'action',
        backdrop: '/images/ott/detail/1075676_bg.png',
        titleLogo: '/images/ott/detail/1075676_logo.png',
    },
    {
        title: '고산자, 대동여지도',
        type: 'movie',
        year: 2016,
        tags: ['sageuk'],
        tmdbId: 410882,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '안시성',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 535389,
        mediaType: 'movie',
        genre: 'action',
    },
];
