// src/tmdb/seeds.jsTV
export const seeds = [
    // TV
    {
        title: '연인',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 206693,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/206693_bg.png',
        titleLogo: '/images/ott/206693_logo.png',
    },
    {
        title: '옷소매 붉은 끝동',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 132925,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/132925_bg.png',
        titleLogo: '/images/ott/132925_logo.png',
    },
    {
        title: '연모',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 129478,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/129478_bg.png',
        titleLogo: '/images/ott/129478_logo.png',
    },
    {
        title: '백일의 낭군님',
        type: 'tv',
        year: 2018,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 81821,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/81821_bg.png',
        titleLogo: '/images/ott/81821_logo.png',
    },
    {
        title: '구르미 그린 달빛',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66256,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/ottdetail.png',
        titleLogo: '/images/ott/title_logo.png',
    },

    {
        title: '신입사관 구해령',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 90721,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/90721_bg.png',
        titleLogo: '/images/ott/90721_logo.png',
    },
    {
        title: '옥씨부인전',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 226649,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/226649_bg.png',
        titleLogo: '/images/ott/226649_logo.png',
    },
    {
        title: '혼례대첩',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 230024,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/230024_bg.png',
        titleLogo: '/images/ott/230024_logo.png',
    },
    {
        title: '킹덤',
        type: 'ott',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 70593,
        mediaType: 'tv',
        genre: 'fantasy',
        backdrop: '/images/ott/70593_bg.png',
        titleLogo: '/images/ott/70593_logo.png',
    },
    {
        title: '조선로코 - 녹두전',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 93541,
        mediaType: 'tv',
        genre: 'fusion',
        backdrop: '/images/ott/93541_bg.png',
        titleLogo: '/images/ott/93541_logo.png',
    },
    {
        title: '폭군의 셰프',
        type: 'tv',
        year: 2025,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 280945,
        mediaType: 'tv',
        genre: 'fantasy',
    },

    {
        title: '고려 거란 전쟁',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 218290,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '화랑',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66496,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '궁',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 5279,
        mediaType: 'tv',
        genre: 'fantasy',
    },

    {
        title: '환혼',
        type: 'tv',
        year: 2022,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 135157,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '철인왕후',
        type: 'tv',
        year: 2020,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 108261,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '달의 연인 - 보보경심 려',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        aka: ['달빛연인'],
        tmdbId: 66433,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '퐁당퐁당 LOVE',
        type: 'tv',
        year: 2015,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 65355,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '옥탑방 왕세자',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 43152,
        mediaType: 'tv',
        genre: 'fantasy',
    },

    {
        title: '낮에 뜨는 달',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 230924,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '귀궁',
        type: 'tv',
        year: 2025,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 259486,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '청춘월담',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 154889,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '열녀박씨 계약결혼뎐',
        type: 'tv',
        year: 2023,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 220076,
        mediaType: 'tv',
        genre: 'fantasy',
    },
    {
        title: '인현왕후의 남자',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 44964,
        mediaType: 'tv',
        genre: 'fantasy',
    },

    {
        title: '장영실',
        type: 'tv',
        year: 2016,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 64811,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '태종 이방원',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 135751,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '불멸의 이순신',
        type: 'tv',
        year: 2004,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 14534,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '태조 왕건',
        type: 'tv',
        year: 2000,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 17039,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '동이',
        type: 'tv',
        year: 2010,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 38852,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '선덕여왕',
        type: 'tv',
        year: 2009,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 21771,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '정도전',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66580,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '연개소문',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 3852,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '광개토태왕',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 39606,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '대왕세종',
        type: 'tv',
        year: 2008,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 14085,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '대장금',
        type: 'tv',
        year: 2003,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 333,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '주몽',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 4734,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '여인천하',
        type: 'tv',
        year: 2001,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 24165,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '이산',
        type: 'tv',
        year: 2007,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 15135,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '해치',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 86094,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '비밀의 문',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61488,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '역적 : 백성을 훔친 도적',
        type: 'tv',
        year: 2017,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 68892,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '왕과 나',
        type: 'tv',
        year: 2007,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 15961,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '장희빈',
        type: 'tv',
        year: 2002,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 70397,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '근초고왕',
        type: 'tv',
        year: 2010,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 35278,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '무신',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 46573,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '마의',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 45049,
        mediaType: 'tv',
        genre: 'orthodox',
    },
    {
        title: '황진이',
        type: 'tv',
        year: 2006,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 565304,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '육룡이 나르샤',
        type: 'tv',
        year: 2015,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 63927,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '해를 품은 달',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 45579,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '뿌리 깊은 나무',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 41652,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '추노',
        type: 'tv',
        year: 2010,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 31424,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '일지매',
        type: 'tv',
        year: 2008,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 21013,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '슈룹',
        type: 'tv',
        year: 2022,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 156406,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '기황후',
        type: 'tv',
        year: 2013,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61148,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '달이 뜨는 강',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 116605,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '군주 - 가면의 주인',
        type: 'tv',
        year: 2017,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 69975,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '7일의 왕비',
        type: 'tv',
        year: 2017,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 71748,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '나의 나라',
        type: 'tv',
        year: 2019,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 93490,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '세작, 매혹된 자들',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 233205,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '왕의 얼굴',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61830,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '조선총잡이',
        type: 'tv',
        year: 2014,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 61184,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '세자가 사라졌다',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 235576,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '장옥정, 사랑에 살다',
        type: 'tv',
        year: 2013,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 47322,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '우씨왕후',
        type: 'tv',
        year: 2024,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 224732,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '공주의 남자',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 40239,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '보쌈-운명을 훔치다',
        type: 'tv',
        year: 2021,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 113623,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '대왕의 꿈',
        type: 'tv',
        year: 2012,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 66719,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '불의 여신 정이',
        type: 'tv',
        year: 2013,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 51866,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '무사 백동수',
        type: 'tv',
        year: 2011,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 40016,
        mediaType: 'tv',
        genre: 'fusion',
    },
    {
        title: '원경',
        type: 'tv',
        year: 2025,
        season: 1,
        tags: ['sageuk'],
        tmdbId: 226103,
        mediaType: 'tv',
        genre: 'fusion',
    },

    // Movie
    {
        title: '사도',
        type: 'movie',
        year: 2015,
        tags: ['sageuk'],
        tmdbId: 315439,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/315439_bg.png',
        titleLogo: '/images/ott/315439_logo.png',
    },
    {
        title: '명량',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 282631,
        mediaType: 'movie',
        genre: 'action',
        backdrop: '/images/ott/282631_bg.png',
        titleLogo: '/images/ott/282631_logo.png',
    },
    {
        title: '한산:용의 출현',
        type: 'movie',
        year: 2022,
        tags: ['sageuk'],
        tmdbId: 588108,
        mediaType: 'movie',
        genre: 'action',
        backdrop: '/images/ott/230024_bg.png',
        titleLogo: '/images/ott/230024_logo.png',
    },
    {
        title: '노량:죽음의 바다',
        type: 'movie',
        year: 2023,
        tags: ['sageuk'],
        tmdbId: 660360,
        mediaType: 'movie',
        genre: 'action',
        backdrop: '/images/ott/660360_bg.png',
        titleLogo: '/images/ott/660360_logo.png',
    },
    {
        title: '관상',
        type: 'movie',
        year: 2013,
        tags: ['sageuk'],
        tmdbId: 220176,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/220176_bg.png',
        titleLogo: '/images/ott/220176_logo.png',
    },
    {
        title: '왕의 남자',
        type: 'movie',
        year: 2005,
        tags: ['sageuk'],
        tmdbId: 45035,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/45035_bg.png',
        titleLogo: '/images/ott/45035_logo.png',
    },
    {
        title: '광해:왕이 된 남자',
        type: 'movie',
        year: 2012,
        tags: ['sageuk'],
        tmdbId: 133200,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/133200_bg.png',
        titleLogo: '/images/ott/133200_logo.png',
    },

    {
        title: '봉이 김선달',
        type: 'movie',
        year: 2016,
        tags: ['sageuk'],
        tmdbId: 385137,
        mediaType: 'movie',
        genre: 'comedy',
        backdrop: '/images/ott/385137_bg.png',
        titleLogo: '/images/ott/3851374_logo.png',
    },
    {
        title: '조선마술사',
        type: 'movie',
        year: 2015,
        tags: ['sageuk'],
        tmdbId: 366654,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/366654_bg.png',
        titleLogo: '/images/ott/366654_logo.png',
    },
    {
        title: '명당',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 544089,
        mediaType: 'movie',
        genre: 'drama',
        backdrop: '/images/ott/544089_bg.png',
        titleLogo: '/images/ott/544089_logo.png',
    },
    {
        title: '조선명탐정:흡혈괴마의 비밀',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 500378,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '궁합',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 500168,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '임금님의 사건수첩',
        type: 'movie',
        year: 2017,
        tags: ['sageuk'],
        tmdbId: 451914,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '군도',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 281780,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '최종병기 활',
        type: 'movie',
        year: 2011,
        tags: ['sageuk'],
        tmdbId: 79224,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '황진이',
        type: 'movie',
        year: 2007,
        tags: ['sageuk'],
        tmdbId: 56247,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '바람과 함께 사라지다',
        type: 'movie',
        year: 2012,
        tags: ['sageuk'],
        tmdbId: 132711,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '나는 왕이로소이다',
        type: 'movie',
        year: 2012,
        tags: ['sageuk'],
        tmdbId: 138713,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '남한산성',
        type: 'movie',
        year: 2017,
        tags: ['sageuk'],
        tmdbId: 437081,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '나랏말싸미',
        type: 'movie',
        year: 2019,
        tags: ['sageuk'],
        tmdbId: 572988,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '전우치',
        type: 'movie',
        year: 2009,
        tags: ['sageuk'],
        tmdbId: 40171,
        mediaType: 'movie',
        genre: 'comedy',
    },
    {
        title: '불꽃처럼 나비처럼',
        type: 'movie',
        year: 2009,
        tags: ['sageuk'],
        tmdbId: 41441,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '신기전',
        type: 'movie',
        year: 2008,
        tags: ['sageuk'],
        tmdbId: 50341,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '올빼미',
        type: 'movie',
        year: 2022,
        tags: ['sageuk'],
        tmdbId: 806128,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '자산어보',
        type: 'movie',
        year: 2021,
        tags: ['sageuk'],
        tmdbId: 581390,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '천문: 하늘에 묻는다',
        type: 'movie',
        year: 2019,
        tags: ['sageuk'],
        tmdbId: 569267,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '해적: 바다로 간 산적',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 285213,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '역린',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 269340,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '상의원',
        type: 'movie',
        year: 2014,
        tags: ['sageuk'],
        tmdbId: 314327,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '전,란',
        type: 'movie',
        year: 2024,
        tags: ['sageuk'],
        tmdbId: 1075676,
        mediaType: 'movie',
        genre: 'action',
    },
    {
        title: '고산자, 대동여지도',
        type: 'movie',
        year: 2016,
        tags: ['sageuk'],
        tmdbId: 410882,
        mediaType: 'movie',
        genre: 'drama',
    },
    {
        title: '안시성',
        type: 'movie',
        year: 2018,
        tags: ['sageuk'],
        tmdbId: 535389,
        mediaType: 'movie',
        genre: 'action',
    },
];
