const ottreviews = [
    {
        id: 1,
        rating: 5,
        nickname: 'mintFox92',
        date: '2025.09.10',
        views: 214,
        likes: 138,
        title: '몰입감 미쳤다… 시간 순삭',
        content: '첫 회부터 박진감 넘침.\n음악-연출 합 너무 좋다.',
        liked: true,
    },
    {
        id: 2,
        rating: 5,
        nickname: 'LunaSea',
        date: '2025.09.08',
        views: 236,
        likes: 145,
        title: '미장센이 예술임',
        content: '색보정 디테일이 미쳤음.\n스샷 수집 중이다.',
        liked: true,
    },
    {
        id: 3,
        rating: 4,
        nickname: '한강개발자',
        date: '2025.09.09',
        views: 146,
        likes: 59,
        title: '배우들 연기 합이 좋아요',
        content: '조연까지 빈 장면이 없었어요.\n연기 합이 정말 좋네요.',
        liked: false,
    },
    {
        id: 4,
        rating: 3,
        nickname: '밤하늘여행자',
        date: '2025.09.07',
        views: 90,
        likes: 18,
        title: '초반은 호, 중반은 루즈',
        content: '중반 템포만 보완되면 좋겠어요.',
        liked: false,
    },
    {
        id: 5,
        rating: 4,
        nickname: 'violetBread',
        date: '2025.09.06',
        views: 164,
        likes: 64,
        title: 'OST가 분위기를 살린다',
        content: '잔상 남는 멜로디라 계속 듣게 됨.',
        liked: false,
    },
    {
        id: 6,
        rating: 5,
        nickname: '새벽감자',
        date: '2025.09.05',
        views: 259,
        likes: 172,
        title: '주인공 서사가 미쳤음',
        content: '동기와 감정선이 설득력 있었습니다.\n대사도 살아있었어요.',
        liked: true,
    },
    {
        id: 7,
        rating: 2,
        nickname: 'saltBagel',
        date: '2025.09.04',
        views: 63,
        likes: 8,
        title: '제 취향엔 좀 과했어요',
        content: '연출이 살짝 과장이라 불호였다.',
        liked: false,
    },
    {
        id: 8,
        rating: 4,
        nickname: '토마토고양이',
        date: '2025.09.03',
        views: 121,
        likes: 37,
        title: '액션 합이 깔끔',
        content: '합 맞춘 느낌이 확실했어요.\n편집 템포도 좋았습니다.',
        liked: false,
    },
    {
        id: 9,
        rating: 5,
        nickname: 'winterGrass',
        date: '2025.09.02',
        views: 198,
        likes: 103,
        title: '엔딩 보고 소리 질렀다',
        content: '반전 납득되고 복선 회수도 깔끔.\n강추다.',
        liked: true,
    },
    {
        id: 10,
        rating: 2,
        nickname: '라일락소다',
        date: '2025.09.01',
        views: 74,
        likes: 15,
        title: '소재는 신선, 전개는 무난',
        content: '설정은 좋았지만 갈등 깊이는 아쉬웠어요.',
        liked: false,
    },
    {
        id: 11,
        rating: 4,
        nickname: 'cloudyMeow',
        date: '2025.08.30',
        views: 129,
        likes: 41,
        title: '대사맛집 인정',
        content: '짧은 대사에 감정 꽉 찼다.\n그 장면 인정.',
        liked: false,
    },
    {
        id: 12,
        rating: 5,
        nickname: '바질티',
        date: '2025.08.29',
        views: 217,
        likes: 139,
        title: '현대극보다 더 생생한 시국감',
        content: '시대 디테일이 살아있네요.\n몰입감이 대단했어요.',
        liked: true,
    },
    {
        id: 13,
        rating: 4,
        nickname: 'cocoBall',
        date: '2025.08.27',
        views: 103,
        likes: 29,
        title: '빌런 보고 싶어서 봄',
        content: '악역 매력이 폭발한다.\n씬스틸러 인정.',
        liked: false,
    },
    {
        id: 14,
        rating: 2,
        nickname: '프리지아',
        date: '2025.08.25',
        views: 78,
        likes: 14,
        title: '편차가 있긴 함',
        content: '회차별 완성도 편차가 있었습니다.',
        liked: false,
    },
    {
        id: 15,
        rating: 5,
        nickname: 'SmokyMusk',
        date: '2025.08.23',
        views: 195,
        likes: 106,
        title: '미친 캐릭터성',
        content: '조연까지 캐릭터 뚜렷함.\n대사도 맛있다.',
        liked: true,
    },
    {
        id: 16,
        rating: 4,
        nickname: '말차크림',
        date: '2025.08.20',
        views: 116,
        likes: 38,
        title: '잔잔한 감정선 좋았어요',
        content: '감정극 좋아하시면 만족하실 듯해요.',
        liked: false,
    },
    {
        id: 17,
        rating: 1,
        nickname: 'peachMojito',
        date: '2025.08.18',
        views: 60,
        likes: 6,
        title: '기대가 커서 더 아쉬움',
        content: '홍보 과했음. 취향 안 맞았다.',
        liked: false,
    },
    {
        id: 18,
        rating: 5,
        nickname: '새벽초',
        date: '2025.08.15',
        views: 238,
        likes: 146,
        title: '연출, 음악, 연기 삼박자',
        content: '큰 장면에서 카타르시스가 대단했어요.\n재탕 각입니다.',
        liked: true,
    },
    {
        id: 19,
        rating: 4,
        nickname: 'PolarisN',
        date: '2025.08.12',
        views: 110,
        likes: 32,
        title: '복선 찾는 재미',
        content: '디테일이 많아서 두 번 보면 더 재밌다.',
        liked: false,
    },
    {
        id: 20,
        rating: 2,
        nickname: '쓴단맛',
        date: '2025.08.10',
        views: 72,
        likes: 12,
        title: '호불호 갈릴 스타일',
        content: '톤이 묵직해서 호불호가 있겠어요.',
        liked: false,
    },
    {
        id: 21,
        rating: 5,
        nickname: 'cinnamonRoll',
        date: '2025.07.30',
        views: 206,
        likes: 126,
        title: '이 조합 또 주세요',
        content: '캐스팅 케미 최고다.\n웃기다 울리다 다 함.',
        liked: true,
    },
    {
        id: 22,
        rating: 4,
        nickname: '귤빛아침',
        date: '2025.07.27',
        views: 118,
        likes: 39,
        title: '미술팀 상줘야 함',
        content: '의상과 세트, 소품 퀄리티가 뛰어났어요.',
        liked: false,
    },
    {
        id: 23,
        rating: 5,
        nickname: 'NightStar7',
        date: '2025.07.24',
        views: 227,
        likes: 151,
        title: '올해 최고작 감',
        content: '몰아보다가 밤샜다.\n만족도 만점.',
        liked: true,
    },
    {
        id: 24,
        rating: 1,
        nickname: '초코칩',
        date: '2025.07.20',
        views: 76,
        likes: 13,
        title: '러브라인은 호불호',
        content: '멜로 비중이 커서 호불호 갈렸어요.',
        liked: false,
    },
    {
        id: 25,
        rating: 4,
        nickname: 'babyBreath',
        date: '2025.07.16',
        views: 131,
        likes: 46,
        title: '대사 한 줄이 오래감',
        content: '심플한 문장이 오래 남는다.',
        liked: false,
    },
    {
        id: 26,
        rating: 5,
        nickname: '우디노트',
        date: '2025.07.12',
        views: 256,
        likes: 164,
        title: '너무 재밌어요.. 주인공 얼굴 밖에 안보여요',
        content: '몰입도, 집중도 최고였어요.\n진짜 시간 순삭이네요.',
        liked: true,
    },
    {
        id: 27,
        rating: 2,
        nickname: 'JellyBear',
        date: '2025.07.08',
        views: 114,
        likes: 36,
        title: '아이와 보기에도 무난',
        content: '폭력 수위 낮고 메시지 선해서 무난함.',
        liked: false,
    },
    {
        id: 28,
        rating: 4,
        nickname: '젤리곰',
        date: '2025.07.05',
        views: 113,
        likes: 35,
        title: '템포가 점점 좋아짐',
        content: '후반으로 갈수록 손맛 살아났어요.',
        liked: false,
    },
    {
        id: 29,
        rating: 5,
        nickname: 'slothDay',
        date: '2025.06.30',
        views: 193,
        likes: 115,
        title: '명대사 폭격',
        content: '클립으로 계속 봄.\n어투 고급지고 찰짐.',
        liked: true,
    },
    {
        id: 30,
        rating: 1,
        nickname: '비온뒤',
        date: '2025.06.26',
        views: 69,
        likes: 7,
        title: '균형 좋은 상업작?',
        content: '저는 별로였어요. 힘이 빠졌습니다.',
        liked: false,
    },
    {
        id: 31,
        rating: 3,
        nickname: 'sandCat22',
        date: '2025.06.22',
        views: 73,
        likes: 11,
        title: '특별하진 않지만 탄탄',
        content: '기본기 탄탄해서 편하게 봤다.',
        liked: false,
    },
    {
        id: 32,
        rating: 4,
        nickname: '바질페스토',
        date: '2025.06.18',
        views: 124,
        likes: 40,
        title: '액션 합이 점점 좋아짐',
        content: '후반 합이 확 좋아졌어요.\n재관람 의사 있습니다.',
        liked: false,
    },
    {
        id: 33,
        rating: 5,
        nickname: 'dawnHerb',
        date: '2025.06.14',
        views: 211,
        likes: 139,
        title: '감정선 직진',
        content: '돌려 말 안 해서 시원했다.',
        liked: true,
    },
    {
        id: 34,
        rating: 4,
        nickname: '클라우드나인',
        date: '2025.06.10',
        views: 117,
        likes: 33,
        title: '카메라 무빙이 맛있음',
        content: '롱테이크를 과감하게 써서 좋았습니다.',
        liked: false,
    },
    {
        id: 35,
        rating: 2,
        nickname: 'peppermint_',
        date: '2025.06.06',
        views: 55,
        likes: 6,
        title: '저는 별로',
        content: '인물 선택 동기가 납득 어렵다.',
        liked: false,
    },
    {
        id: 36,
        rating: 5,
        nickname: '단단한돌',
        date: '2025.06.02',
        views: 231,
        likes: 153,
        title: '이 조합 또 보자',
        content: '배우·연출·음악의 합이 완벽했어요.\n다음 시즌 가시죠.',
        liked: true,
    },
    {
        id: 37,
        rating: 4,
        nickname: 'todayTea',
        date: '2025.05.29',
        views: 121,
        likes: 39,
        title: '대사 맛과 표정 연기',
        content: '눈빛으로 감정 다 전달되더라.',
        liked: false,
    },
    {
        id: 38,
        rating: 1,
        nickname: '윤슬',
        date: '2025.05.24',
        views: 52,
        likes: 5,
        title: '장단이 분명',
        content: '킬포는 있지만 전반적으로는 불호였어요.',
        liked: false,
    },
    {
        id: 39,
        rating: 4,
        nickname: 'gingerCookie',
        date: '2025.05.20',
        views: 126,
        likes: 44,
        title: '가족이랑 보기 좋아요',
        content: '폭력 수위 낮고 메시지가 선했다.',
        liked: false,
    },
    {
        id: 40,
        rating: 5,
        nickname: '밤바다',
        date: '2025.05.16',
        views: 214,
        likes: 135,
        title: '주말 몰아보기 강추',
        content: '엔딩이 후련했어요.\n기분 좋아졌습니다.',
        liked: true,
    },
    {
        id: 41,
        rating: 2,
        nickname: 'gamjaBear',
        date: '2025.04.30',
        views: 51,
        likes: 4,
        title: '의상 맛집?',
        content: '난 별로였다. 색감 과함.',
        liked: false,
    },
    {
        id: 42,
        rating: 3,
        nickname: '수프카레',
        date: '2025.04.24',
        views: 75,
        likes: 12,
        title: '연출은 좋은데 각본이 살짝',
        content: '동기부여가 조금 더 탄탄했으면 좋겠어요.',
        liked: false,
    },
    {
        id: 43,
        rating: 5,
        nickname: 'LavenderField',
        date: '2025.04.18',
        views: 198,
        likes: 124,
        title: '한 장면 한 장면이 명화',
        content: '프레임 구성이 미쳤다.\n캡처 욕구 자극.',
        liked: true,
    },
    {
        id: 44,
        rating: 4,
        nickname: '솜사탕',
        date: '2025.04.12',
        views: 120,
        likes: 37,
        title: '대본의 힘',
        content: '대사로 서사를 끌어가는 맛이 있었어요.',
        liked: false,
    },
    {
        id: 45,
        rating: 1,
        nickname: 'blkCoffee',
        date: '2025.03.28',
        views: 50,
        likes: 4,
        title: '저한텐 과했어요',
        content: '과장된 연출이라 보기 피곤했다.',
        liked: false,
    },
    {
        id: 46,
        rating: 5,
        nickname: '달구지',
        date: '2025.03.20',
        views: 221,
        likes: 146,
        title: '완성도 최상',
        content: '연출·촬영·음악·연기 모두 상급이었어요.\n퀄리티 안정적이네요.',
        liked: true,
    },
    {
        id: 47,
        rating: 2,
        nickname: 'rainbowShell',
        date: '2025.02.14',
        views: 122,
        likes: 41,
        title: '결말 좋았다',
        content: '깔끔하게 매듭지어서 후련했다.',
        liked: false,
    },
    {
        id: 48,
        rating: 3,
        nickname: '고래꿈',
        date: '2025.02.05',
        views: 70,
        likes: 11,
        title: '중반부만 넘기면 OK',
        content: '초반 러닝이 길었지만 후반에 몰아쳤어요.',
        liked: false,
    },
    {
        id: 49,
        rating: 1,
        nickname: 'sunsetVibe',
        date: '2025.01.15',
        views: 48,
        likes: 3,
        title: '연휴에 보기 딱?',
        content: '기대 이하였다. 재관람 의사 없음.',
        liked: false,
    },
    {
        id: 50,
        rating: 5,
        nickname: '새봄',
        date: '2025.01.01',
        views: 205,
        likes: 131,
        title: '이건 무조건 보세요',
        content: '시간 아깝단 생각 안 들었어요.\n정말 추천드립니다.',
        liked: true,
    },
];

export default ottreviews;
