export const tourclassData = [
  {
    id: 1,
    category: "tour",
    title: "경복궁 달빛기행",
    theme: ["역사", "예술"],
    description: "경복궁 내 투어 및 공연관람",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "외소주방",
      "자경전&흥복전",
      "장고",
      "집옥재&팔우정",
      "건청궁",
      "향원정",
    ],
    price: 54000,
    quantity: 1,
    img: "/images/tourclass/tourImg/01.png",
    detailsub1:
      "고요한 밤, 달빛 아래 고궁을 거닐며 조선의 숨결을 마주하는 시간",
    detailsub2: "궁궐의 은은한 조명과 함께 전통 예술공연까지 즐길 수 있습니다.",
  },
  {
    id: 2,
    category: "tour",
    title: "남한산성 행궁의 역사산책",
    theme: ["힐링", "역사"],
    description: "남한산성 투어 및 도예체험",
    period: "하루",
    time: "상시예약",
    region: "경기도 광주시",
    place: ["남한산성", "청와정 카페", "도자공방 오롯"],
    price: 32000,
    quantity: 1,
    img: "/images/tourclass/tourImg/02.png",
    detailsub1:
      "산과 성벽이 어우러진 고즈넉한 남한산성에서 조선의 시간을 걸어요.",
    detailsub2:
      "아늑한 공방에서 흙을 빚으며 나만의 전통 도자기를 완성해보세요!",
  },
  {
    id: 3,
    category: "tour",
    title: "익선동 한옥거리 미식 산책",
    theme: ["라이프"],
    description: "전통, 모던 감성 섞인 한옥 데이트",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: ["익선동 골목길", "옛날 다방", "청계천"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/03.png",
    detailsub1:
      "전통 한옥과 감성 카페가 공존하는 익선동 골목을 따라 걷는 미식 여행",
    detailsub2: "청계천까지 이어지는 산책길과 함께 레트로한 감성을 느껴보세요.",
  },
  {
    id: 4,
    category: "tour",
    title: "전통과 현대를 잇는 예술여행",
    theme: ["융합", "예술"],
    description: "전통, 모던 감성의 미술관/박물관 투어",
    period: "1박 2일",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "서울공예박물관",
      "북촌 한옥마을",
      "국립현대미술관",
      "리움미술관",
      "서울시립미술관",
      "남산골 한옥마을",
    ],
    price: 100000,
    quantity: 1,
    img: "/images/tourclass/tourImg/04.png",
    detailsub1: "서울 곳곳에 숨은 전통과 현대 미술을 한 번에 만나는 예술 여정",
    detailsub2:
      "미술관과 박물관을 넘나들며 창조적 감성을 깊이 있게 체험합니다.",
  },
  {
    id: 5,
    category: "tour",
    title: "운현궁의 비밀스러운 하루",
    theme: ["역사", "라이프"],
    description: "운현궁 투어 및 전통문화체험",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: ["운현궁", "인사동 거리", "쌈지길", "익선동 한옥거리"],
    price: 56000,
    quantity: 1,
    img: "/images/tourclass/tourImg/05.png",
    detailsub1:
      "고종의 아버지 흥선대원군의 자취가 깃든 운현궁에서 시작하는 시간 여행",
    detailsub2:
      "한옥골목, 전통체험, 예술공방까지 문화가 흐르는 하루를 선물합니다.",
  },
  {
    id: 6,
    category: "tour",
    title: "북촌 로맨스, K-드라마 속으로",
    theme: ["융합"],
    description: "북촌 한옥마을 속 K-드라마 촬영지 투어",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: ["가회동 돌담길", "가회동 한옥체험관", "익선동 한옥거리"],
    price: 66000,
    quantity: 1,
    img: "/images/tourclass/tourImg/06.png",
    detailsub1:
      "K-드라마 명장면 속 감성이 살아 숨 쉬는 북촌의 길을 따라 걷습니다.",
    detailsub2:
      "한옥 사이로 흐르는 낭만과 함께 드라마처럼 특별한 하루를 보내세요!",
  },
  {
    id: 7,
    category: "tour",
    title: "조선왕조 이야기, 궁궐을 걷다",
    theme: ["역사", "힐링"],
    description: "종로구 궁궐 투어 및 한옥 홈스테이",
    period: "1박 2일",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "경복궁",
      "국립민속박물관",
      "북촌 한옥마을",
      "덕수궁",
      "광화문",
      "서울역사박물관",
    ],
    price: 98000,
    quantity: 1,
    img: "/images/tourclass/tourImg/07.png",
    detailsub1:
      "서울 도심 속에서 조선의 궁궐들을 따라 왕조의 역사와 일상을 만납니다.",
    detailsub2:
      "한옥 홈스테이에서 하룻밤을 보내며 전통의 시간을 온몸으로 느껴보세요!",
  },
  {
    id: 8,
    category: "tour",
    title: "천년의 숨결, 경주 전통기행",
    theme: ["라이프", "역사", "융합"],
    description: "경주에서 즐기는 전통문화와 역사, 맛 여행",
    period: "2박 3일",
    time: "상시예약",
    region: "경상북도 경주시",
    place: [
      "경주 교촌한옥마을",
      "미경 전통식문화연구소",
      "경주 미정당",
      "한옥스테이",
      "국립경주박물관",
      "황리단길",
    ],
    price: 154000,
    quantity: 1,
    img: "/images/tourclass/tourImg/08.png",
    detailsub1:
      "신라 천년의 수도 경주에서 유서 깊은 문화유산과 한옥의 정취를 만끽하세요.",
    detailsub2:
      "전통 음식 체험부터 역사 박물관 관람까지 깊이 있는 여정이 펼쳐집니다!",
  },
  {
    id: 9,
    category: "tour",
    title: "수원 화성,\n행궁동 골목길 시간 여행",
    theme: ["역사", "힐링"],
    description: "수원 화성 투어",
    period: "하루",
    time: "상시예약",
    region: "경기도 수원시",
    place: ["화성행굴", "행궁동", "팔달문"],
    price: 48000,
    quantity: 1,
    img: "/images/tourclass/tourImg/09.png",
    detailsub1:
      "정조의 애민정신이 깃든 수원 화성과 옛 골목의 이야기를 따라 걷는 여행",
    detailsub2: "팔달문 시장의 정겨운 풍경과 함께 시간을 거슬러 올라가 보세요.",
  },
  {
    id: 10,
    category: "tour",
    title: "파주, 예술이 피어나는 길",
    theme: ["예술", "힐링", "융합"],
    description: "파주에서 느끼는 예술의 길",
    period: "1박 2일",
    time: "상시예약",
    region: "경기도 파주시",
    place: [
      "헤이리 예술마을",
      "뮤지엄 모아",
      "아트팩토리",
      "헤이리 골목",
      "파주출판도시",
      "임진각",
    ],
    price: 79000,
    quantity: 1,
    img: "/images/tourclass/tourImg/10.png",
    detailsub1:
      "헤이리 마을과 출판도시의 창작 공간을 탐험하며 감성을 채우는 여행",
    detailsub2:
      "예술, 책, 자연이 조화롭게 어우러진 문화 힐링 코스를 경험하세요.",
  },
  {
    id: 11,
    category: "tour",
    title: "빛과 자연의 원주",
    theme: ["힐링", "예술"],
    description: "뮤지엄산 관람과 원주 대표 관광지 체험",
    period: "하루",
    time: "상시예약",
    region: "강원도 원주시",
    place: ["뮤지엄산", "소금산 출렁다리", "원주 중앙시장"],
    price: 68000,
    quantity: 1,
    img: "/images/tourclass/tourImg/11.png",
    detailsub1:
      "자연과 예술이 만나는 뮤지엄산에서 감성 충전의 시간을 즐겨보세요!",
    detailsub2:
      "출렁다리에서의 스릴과 전통시장 속 향토의 매력을 함께 느껴봅니다.",
  },
  {
    id: 12,
    category: "tour",
    title: "소양강 위에서, 춘천의 시간",
    theme: ["힐링", "역사"],
    description: "국립춘천박물관 관람과 호수 도시 춘천 체험",
    period: "하루",
    time: "상시예약",
    region: "강원도 춘천시",
    place: ["국립춘천박물관", "소양강 스카이워크", "애니메이션박물관"],
    price: 58000,
    quantity: 1,
    img: "/images/tourclass/tourImg/12.png",
    detailsub1:
      "춘천 호반의 도시에서 역사와 문화, 자연을 두루 만나는 감성 여행",
    detailsub2:
      "유유히 흐르는 소양강 위를 걷고, 애니메이션 속 상상력을 느껴보세요.",
  },
  {
    id: 13,
    category: "tour",
    title: "파도와 예술이 머무는\n강릉 1박2일",
    theme: ["예술", "힐링"],
    description: "강릉시립미술관 관람과 바다·전통·카페거리 체험",
    period: "1박 2일",
    time: "상시예약",
    region: "강원도 강릉시",
    place: [
      "강릉시립미술관",
      "강릉 오죽헌",
      "강릉 중앙시장",
      "경포호수",
      "선교장",
      "주문진 방파제",
    ],
    price: 99000,
    quantity: 1,
    img: "/images/tourclass/tourImg/13.png",
    detailsub1: "동해 바다를 따라 예술과 전통이 어우러지는 강릉의 감성 여정",
    detailsub2:
      "고즈넉한 오죽헌부터 핫한 카페거리까지, 모든 풍경이 그림이 됩니다.",
  },
  {
    id: 14,
    category: "tour",
    title: "파도 따라 걷는 속초·양양 아트로드",
    theme: ["예술", "힐링"],
    description: "동해안 박물관·미술관과 해변 감성 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "강원도 속초시",
    place: [
      "속초시립박물관",
      "속초 중앙시장",
      "청초호 호수공원",
      "일현미술관",
      "낙산사",
      "서피비치 카페거리",
    ],
    price: 110000,
    quantity: 1,
    img: "/images/tourclass/tourImg/14.png",
    detailsub1: "동해의 푸른 바다와 예술이 함께하는 속초·양양 감성 여행 코스",
    detailsub2:
      "미술관과 사찰, 바다와 시장을 모두 담은 감동 가득한 하루를 선사합니다.",
  },
  {
    id: 15,
    category: "tour",
    title: "보은·청주,\n전통과 예술이 만나는 여행",
    theme: ["예술", "역사"],
    description: "속리산 법주사의 전통과 현대 예술을 잇는 문화여행",
    period: "1박 2일",
    time: "상시예약",
    region: "충청북도 청주시",
    place: [
      "속리산 법주사",
      "상단산성",
      "육거리종합시장",
      "청주공예비엔날레",
      "청주시립미술관",
      "공예비엔날레",
    ],
    price: 96000,
    quantity: 1,
    img: "/images/tourclass/tourImg/15.png",
    detailsub1:
      "천년 고찰 속리산 법주사에서 시작해 청주의 현대예술을 만납니다.",
    detailsub2:
      "시장 골목의 활기와 비엔날레의 창조적 감각이 하나로 이어집니다!",
  },
  {
    id: 16,
    category: "tour",
    title: "별빛과 역사가 머무는\n영월 1박2일",
    theme: ["역사", "라이프"],
    description: "전통 + 모던 감성 섞인 한옥 데이트",
    period: "1박 2일",
    time: "상시예약",
    region: "강원도 영월군",
    place: [
      "난고김삿갓문학관",
      "단종역사관",
      "동강사진박물관",
      "별마로천문대",
      "라디오스타박물관",
      "동강생태정보센터",
    ],
    price: 84000,
    quantity: 1,
    img: "/images/tourclass/tourImg/16.png",
    detailsub1: "영월의 시와 역사, 별빛과 자연이 어우러진 서정적 문화 기행",
    detailsub2: "문학관부터 천문대까지, 감성으로 가득한 밤과 낮이 펼쳐집니다.",
  },
  {
    id: 17,
    category: "tour",
    title: "문학과 자연이 흐르는 인제 하루",
    theme: ["예술"],
    description: "서예·문학관람과 내설악 풍경 감상",
    period: "하루",
    time: "상시예약",
    region: "강원도 인제군",
    place: ["여초서예관", "내설악미술관", "백담사"],
    price: 54000,
    quantity: 1,
    img: "/images/tourclass/tourImg/17.png",
    detailsub1:
      "산자락 품은 인제에서 서예와 문학, 그리고 고요한 자연을 만납니다.",
    detailsub2:
      "백담사의 고즈넉함과 내설악의 절경 속에서 마음이 깊어지는 하루예요!",
  },
  {
    id: 18,
    category: "tour",
    title: "백제의 고도 공주 여행",
    theme: ["역사"],
    description: "백제의 고도 숨결이 흐르는 금강여행",
    period: "1박 2일",
    time: "상시예약",
    region: "충청남도 공주시",
    place: [
      "국립공주박물관",
      "무령왕릉",
      "공주 한옥마을",
      "공산성",
      "공주 시장",
      "금강변",
    ],
    price: 120000,
    quantity: 1,
    img: "/images/tourclass/tourImg/18.png",
    detailsub1: "고대 백제의 찬란한 문화와 유산을 따라 걷는 시간 여행의 시작",
    detailsub2:
      "강변의 낭만과 함께 한옥에서 하룻밤 머무는 특별한 경험이 기다립니다.",
  },
  {
    id: 19,
    category: "tour",
    title: "청주 도심 문화 예술 하루여행",
    theme: ["예술", "힐링"],
    description: "역사와 예술이 숨쉬는 청주의 예술여행",
    period: "하루",
    time: "상시예약",
    region: "충청북도 청주시",
    place: ["국립청주박물관", "청주 성안길", "청주공예비엔날레"],
    price: 48000,
    quantity: 1,
    img: "/images/tourclass/tourImg/19.png",
    detailsub1: "청주 도심 속에서 만나는 전통과 현대가 어우러진 예술 감성 투어",
    detailsub2:
      "성안길 골목과 공예비엔날레 전시를 통해 문화의 숨결을 느껴보세요.",
  },
  {
    id: 20,
    category: "tour",
    title: "백제 로맨스, 부여 1박 2일",
    theme: ["힐링", "융합"],
    description: "여전히 아름다운 백제의 꽃, 숨은 핫플 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "충청남도 부여군",
    place: [
      "국립부여박물관",
      "부소산성",
      "전통시장",
      "한옥길",
      "능산리 고군분",
      "백제왕릉원",
    ],
    price: 108000,
    quantity: 1,
    img: "/images/tourclass/tourImg/20.png",
    detailsub1: "로맨틱한 백제 문화유산을 배경으로 펼쳐지는 부여의 감성 여행",
    detailsub2:
      "역사의 향기와 핫플이 공존하는 부여에서 특별한 하루를 경험해보세요.",
  },
  {
    id: 21,
    category: "tour",
    title: "현대예술과 청춘 감성 하루여행",
    theme: ["예술", "라이프"],
    description: "미술관부터 공원 산책, 역사와 예술을 걷다",
    period: "하루",
    time: "상시예약",
    region: "충청북도 청주시",
    place: ["청주시립미술관", "문화예술창작촌", "청주 성안길"],
    price: 60000,
    quantity: 1,
    img: "/images/tourclass/tourImg/21.png",
    detailsub1: "도심 속 미술관과 창작촌을 따라 걷는 청춘 감성 문화 산책",
    detailsub2: "청주의 예술과 일상, 그리고 청춘의 에너지를 동시에 느껴보세요.",
  },
  {
    id: 22,
    category: "tour",
    title: "전통과 현대가 어우러진\n용인 하루",
    theme: ["라이프"],
    description: "한국민속촌 체험과 용인 대표 명소 탐방",
    period: "하루",
    time: "상시예약",
    region: "경기도 용인시",
    place: ["한국민속촌", "에버랜드", "호암미술관"],
    price: 58000,
    quantity: 1,
    img: "/images/tourclass/tourImg/22.png",
    detailsub1: "한국민속촌에서 전통을 체험하고, 현대의 즐거움을 더해보는 하루",
    detailsub2: "에버랜드의 활기와 호암미술관의 정적인 감동이 조화를 이룹니다.",
  },
  {
    id: 23,
    category: "tour",
    title: "호수와 예술이 머무는 안산 하루",
    theme: ["예술", "힐링"],
    description: "경기도미술관 관람과 호수·바다 감성 여행",
    period: "하루",
    time: "상시예약",
    region: "경기도 안산시",
    place: ["경기도미술관", "안산호수공원", "안산갈대습지공원"],
    price: 48000,
    quantity: 1,
    img: "/images/tourclass/tourImg/23.png",
    detailsub1: "호수와 갈대숲, 예술로 채워지는 안산의 감성 힐링 코스",
    detailsub2: "도심 속 자연과 전시를 함께 즐기며 여유로운 시간을 보내보세요.",
  },
  {
    id: 24,
    category: "tour",
    title: "송도, 전통과 미래가 만나는 길",
    theme: ["라이프"],
    description: "송도 한옥마을과 송도 국제도시 체험",
    period: "하루",
    time: "상시예약",
    region: "인천 연수구",
    place: ["송도 한옥마을", "송도 센트럴파크", "G타워 전망대"],
    price: 51000,
    quantity: 1,
    img: "/images/tourclass/tourImg/24.png",
    detailsub1: "한옥의 정취와 미래 도시의 세련미가 공존하는 송도 감성 여행",
    detailsub2:
      "센트럴파크 산책과 전망대에서 바라보는 도심 풍경이 인상적입니다.",
  },
  {
    id: 25,
    category: "tour",
    title: "한국 전통의 모든 것, 국립중앙박물관 스탬프투어",
    theme: ["역사", "예술"],
    description: "스탬프 투어와 전통을 통한 한국의 역사와 문화 체험",
    period: "하루",
    time: "상시예약",
    region: "서울 용산구",
    place: ["국립중앙박물관", "한국관", "불교미술관"],
    price: 38000,
    quantity: 1,
    img: "/images/tourclass/tourImg/25.png",
    detailsub1:
      "국립중앙박물관에서 펼쳐지는 한국 전통문화의 진수를 경험하세요!",
    detailsub2:
      "스탬프 투어를 따라 역사와 예술의 흐름을 직접 체험할 수 있습니다.",
  },
  {
    id: 26,
    category: "tour",
    title: "현대미술과 도심 속\n감각적인 하루",
    theme: ["예술", "라이프"],
    description: "현대미술 전시와 덕수궁 돌담길, 도심 문화 체험",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: ["국립현대미술관", "덕수궁 돌담길", "서울시립미술관", "정동극장"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/26.png",
    detailsub1: "도심 속에서 만나는 현대미술과 고궁이 어우러진 감각적인 하루",
    detailsub2: "돌담길과 극장을 따라 걸으며 예술과 낭만을 동시에 누려보세요.",
  },
  {
    id: 27,
    category: "tour",
    title: "역사의 숨결, 나주 하루",
    theme: ["역사"],
    description: "국립나주박물관 관람과 나주 고대 역사 탐방",
    period: "하루",
    time: "상시예약",
    region: "전라남도 나주시",
    place: ["국립나주박물관", "나주읍성", "금성관", "빛가람 혁신도시 카페거리"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/27.png",
    detailsub1: "고대 마한과 나주의 역사를 품은 유적지를 따라 걷는 하루",
    detailsub2: "전통과 현재가 이어지는 나주의 숨은 매력을 발견해보세요.",
  },
  {
    id: 28,
    category: "tour",
    title: "백제의 기억, 익산 하루",
    theme: ["역사"],
    description: "국립익산박물관과 미륵사지 탐방",
    period: "하루",
    time: "상시예약",
    region: "전라북도 익산시",
    place: ["국립익산박물관", "미륵사지", "왕궁리 유적"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/28.png",
    detailsub1: "백제의 기억이 살아 숨 쉬는 익산에서의 고대 문화탐방",
    detailsub2: "미륵사지의 웅장함과 박물관의 깊이를 동시에 체험할 수 있어요.",
  },
  {
    id: 29,
    category: "tour",
    title: "예술과 자연의 조화, 완주 하루",
    theme: ["예술"],
    description: "전북도립미술관과 예술촌 탐방",
    period: "하루",
    time: "상시예약",
    region: "전라북도 완주군",
    place: ["전북도립미술관", "삼례문화예술촌", "대둔산"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/29.png",
    detailsub1: "완주의 자연 속에서 만나는 예술, 그리고 마음이 쉬어가는 시간",
    detailsub2: "대둔산의 절경과 예술촌의 창의성이 감성을 가득 채워줍니다.",
  },
  {
    id: 30,
    category: "tour",
    title: "시간이 머무는 길, 전주 1박2일",
    theme: ["역사", "라이프"],
    description: "전주 한옥마을과 경기전, 전통음식 투어",
    period: "1박 2일",
    time: "상시예약",
    region: "전라북도 전주시",
    place: ["전주 경기전", "전주 한옥마을", "국립전주박물관", "향교길"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/30.png",
    detailsub1: "전주의 고즈넉한 한옥길과 전통문화가 어우러진 감성 여행",
    detailsub2: "경기전과 향교길을 따라 옛 정취와 맛을 깊이 있게 느껴보세요.",
  },
  {
    id: 31,
    category: "tour",
    title: "예술의 파동, 광주에서 시작되다",
    theme: ["예술", "융합"],
    description:
      "국립광주박물관, 아시아문화전당, 광주비엔날레 포함 예술·역사 투어",
    period: "2박 3일",
    time: "상시예약",
    region: "광주",
    place: [
      "국립광주박물관",
      "펭귄마을",
      "무등산 자락 카페",
      "국립아시아문화전당",
      "양림동 역사문화마을",
      "광주시립미술관",
      "광주비엔날레",
      "5·18기념관",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/31.png",
    detailsub1:
      "광주의 예술과 민주주의 정신이 흐르는 도시 전체가 갤러리인 여행",
    detailsub2:
      "비엔날레와 아시아문화전당, 역사 깊은 골목까지 폭넓게 경험해보세요.",
  },
  {
    id: 32,
    category: "tour",
    title: "남강의 등불, 진주 역사 하루여행",
    theme: ["역사", "힐링"],
    description:
      "역사와 전통을 담은 국립진주박물관 관람과 남강 야경으로 즐기는 진주 하루 여행",
    period: "하루",
    time: "상시예약",
    region: "경상남도 진주시",
    place: [
      "국립진주박물관",
      "촉석루",
      "진주남강유등전 기념 전시관",
      "남강 중앙시장",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/32.png",
    detailsub1:
      "남강을 따라 흐르는 유등의 빛, 전통과 야경이 어우러진 진주 역사산책",
    detailsub2:
      "촉석루와 유등 전시관까지, 조용하지만 깊이 있는 하루를 만끽하세요.",
  },
  {
    id: 33,
    category: "tour",
    title: "대구의 시간, 신라에서 근대까지",
    theme: ["역사", "라이프"],
    description: "역사와 예술, 김광석 거리와 팔공산을 즐기는 대구 1박 2일 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "대구",
    place: [
      "국립대구박물관",
      "근대문화골목",
      "김광석 다시그리기길",
      "팔공산 동화사",
      "대구 수성못 카페거리",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/33.png",
    detailsub1: "신라의 기운부터 근대 문화골목까지, 대구의 시간 속을 걷는 여정",
    detailsub2:
      "김광석 거리의 감성과 팔공산의 고요함이 특별한 1박 2일을 만들어줍니다.",
  },
  {
    id: 34,
    category: "tour",
    title: "하회마을, 탈춤과 풍류의 길",
    theme: ["역사", "힐링"],
    description:
      "전통 한옥과 탈춤, 유네스코 서원과 월영교를 즐기는 안동 1박 2일 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "경상북도 안동시",
    place: ["안동 하회마을", "병산서원", "월영교"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/34.png",
    detailsub1:
      "유네스코가 인정한 하회마을과 서원에서 전통의 깊이를 느껴보세요!",
    detailsub2: "월영교의 야경과 안동의 풍류가 어우러진 감성 힐링 여행입니다.",
  },
  {
    id: 35,
    category: "tour",
    title: "바다 위의 예술,\n부산비엔날레 하루",
    theme: ["예술", "라이프"],
    description: "현대미술과 역사, 해변 노을을 즐기는 부산 하루 여행",
    period: "하루",
    time: "상시예약",
    region: "부산",
    place: [
      "부산비엔날레",
      "남포동 카페거리",
      "부산근현대역사관",
      "광안리 해변",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/35.png",
    detailsub1: "바다와 현대예술이 만나는 부산 비엔날레 중심의 문화 산책",
    detailsub2: "광안리 해변 노을과 함께, 도심 속 미술과 역사를 경험해보세요.",
  },
  {
    id: 36,
    category: "tour",
    title: "철길 위의 예술, F1963 투어",
    theme: ["예술", "융합"],
    description:
      "예술 전시장과 감각적인 카페 거리, 야경을 즐기는 부산 하루 여행",
    period: "하루",
    time: "상시예약",
    region: "부산",
    place: [
      "F1963",
      "수영강 카페거리",
      "망미동 카페거리",
      "센텀시티 영화의 전당",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/36.png",
    detailsub1: "버려진 철길이 문화예술 공간으로 재탄생한 감각적 부산의 하루",
    detailsub2:
      "F1963과 카페거리, 센텀시티의 풍경이 어우러진 트렌디한 코스입니다.",
  },
  {
    id: 37,
    category: "tour",
    title: "미래를 그리는 도시, 울산 예술여행",
    theme: ["예술", "힐링"],
    description:
      "미디어아트와 고래문화, 태화강 야경과 간절곶 일출을 즐기는 울산 1박 2일 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "울산",
    place: [
      "울산시립미술관",
      "울산 중앙시장",
      "장생포 고래문화마을",
      "태화강 국가정원",
      "간절곶",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/37.png",
    detailsub1: "미디어아트와 고래 문화가 어우러진 울산의 미래지향적 문화 여행",
    detailsub2:
      "태화강 야경부터 간절곶 일출까지, 자연과 예술을 모두 누려보세요.",
  },
  {
    id: 38,
    category: "tour",
    title: "개실마을, 느린 발걸음의 하루",
    theme: ["역사", "힐링"],
    description: "전통 한옥과 대가야 역사, 강변 산책을 즐기는 고령 하루 여행",
    period: "하루",
    time: "상시예약",
    region: "경상북도 고령군",
    place: ["고령 개실마을", "대가야 역사테마관광지", "낙동강"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/38.png",
    detailsub1: "대가야의 역사를 품은 고즈넉한 개실마을에서의 느린 하루",
    detailsub2:
      "역사 테마와 낙동강 산책이 어우러지는 고령의 진한 멋을 느껴보세요.",
  },
  {
    id: 39,
    category: "tour",
    title: "한글에서 한옥까지,\n한국문화 오감 여행",
    theme: ["역사", "힐링"],
    description:
      "한글박물관부터 전통음식·공예·한옥길까지 한국 멋 체험 하루 투어",
    period: "하루",
    time: "상시예약",
    region: "서울시 용산구",
    place: ["국립한글박물관", "경복궁", "인사동", "북촌 한옥마을", "청계천"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/39.png",
    detailsub1:
      "한글, 한옥, 전통음식까지 한국의 문화정수를 오감으로 체험하는 하루",
    detailsub2:
      "도심 속 전통길과 북촌, 인사동에서 진짜 한국의 멋을 만나보세요.",
  },
  {
    id: 40,
    category: "tour",
    title: "놀며 배우는 한국문화:\n어린이 민속 체험 하루여행",
    theme: ["역사", "융합"],
    description: "어린이박물관에서 시작하는 전통놀이·공예·간식 체험 투어",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "국립민속박물관 어린이박물관",
      "북촌 한옥마을",
      "인사동 전통문화거리",
      "청계천",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/40.png",
    detailsub1:
      "어린이를 위한 맞춤 전통 체험으로 한국문화를 쉽고 재미있게 배워요!",
    detailsub2:
      "민속박물관부터 인사동·한옥길까지 교육과 놀이가 함께하는 여행입니다.",
  },
  {
    id: 41,
    category: "tour",
    title: "예술과 한옥정원,\n그리고 손끝 체험",
    theme: ["예술", "융합"],
    description: "석파정과 북촌 공예, 고궁 산책을 아우르는 한국문화 투어",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "석파정 서울미술관",
      "북촌 한옥마을",
      "인사동 전통문화거리",
      "경복궁",
      "광화문 전통시장",
      "국립민속박물관",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/41.png",
    detailsub1: "예술, 정원, 공예가 어우러진 서울 도심 속 깊이 있는 문화 산책",
    detailsub2:
      "석파정의 미술과 북촌의 손끝 예술까지, 한국의 멋을 오감으로 즐겨보세요.",
  },
  {
    id: 42,
    category: "tour",
    title: "바다와 예술의 만남,\n부산 아트 데이",
    theme: ["예술", "라이프"],
    description: "현대미술과 광안리 바다 풍경을 함께 즐기는 하루 예술 산책",
    period: "하루",
    time: "상시예약",
    region: "부산",
    place: ["부산시립미술관", "영화의 전당", "광안리 해변"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/42.png",
    detailsub1: "푸른 바다와 현대미술의 만남, 감성 가득한 부산의 하루",
    detailsub2: "광안리 해변과 미술관이 어우러지는 여유로운 아트 산책입니다.",
  },
  {
    id: 43,
    category: "tour",
    title: "대구, 예술의 빛과 근대의 길",
    theme: ["역사", "예술"],
    description: "미술 전시와 근대골목, 팔공산까지 아우르는 역사·예술 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "대구",
    place: [
      "대구미술관",
      "김광석 다시그리기길",
      "팔공산 동화사",
      "수성못 카페거리",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/43.png",
    detailsub1: "미술과 근대문화가 함께하는 대구의 역사·예술 1박 2일",
    detailsub2: "김광석 거리의 감성과 팔공산의 고요함을 모두 경험해보세요.",
  },
  {
    id: 44,
    category: "tour",
    title: "과학과 예술의 융합,\n대전 아트 투어",
    theme: ["예술", "융합"],
    description: "미술·과학·도시문화를 연결한 대전만의 융합형 투어",
    period: "1박 2일",
    time: "상시예약",
    region: "대전",
    place: [
      "대전시립미술관",
      "이응노미술관",
      "성심당",
      "대전 엑스포과학공원",
      "으능정이거리",
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/44.png",
    detailsub1: "예술과 과학, 그리고 대전의 도시감성이 만나는 융합 여행",
    detailsub2:
      "미술관, 과학공원, 로컬 명소가 어우러진 신개념 문화 투어입니다.",
  },
  {
    id: 45,
    category: "tour",
    title: "올림픽공원 속 예술 산책",
    theme: ["예술", "힐링"],
    description: "공원 속 미술관과 조각공원, 산책이 어우러진 힐링 예술 여행",
    period: "하루",
    time: "상시예약",
    region: "서울시 송파구",
    place: ["소마미술관", "올림픽공원", "석촌호수"],
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/45.png",
    detailsub1: "도심 속 공원에서 예술과 힐링을 동시에 느끼는 하루 여행",
    detailsub2: "소마미술관과 조각공원, 석촌호수를 따라 여유롭게 걸어보세요.",
  },
  {
    id: 46,
    category: "tour",
    title: "손끝의 전통, 공예와 하루",
    theme: ["역사", "예술", "라이프"],
    description: "전통 공예의 아름다움과 북촌·인사동 감성을 느끼는 하루",
    region: "서울 종로구",
    place: ["서울공예박물관", "북촌 한옥마을", "인사동 전통문화거리"],
    period: "하루",
    time: "상시예약",
    price: 30000,
    quantity: 1,
    img: "/images/tourclass/tourImg/46.png",
    detailsub1: "전통 공예와 한옥 감성, 손끝으로 느끼는 서울의 멋",
    detailsub2: "공예박물관부터 인사동까지, 정겨운 전통의 하루를 체험하세요.",
  },
  {
    id: 47,
    category: "tour",
    title: "한옥과 국악, 전통의 하루",
    theme: ["역사", "라이프"],
    description:
      "한옥마을과 국악 공연, 궁궐 돌담길을 함께 즐기는 도심 전통 산책",
    region: "서울시 종로구",
    place: ["돈화문한옥마을", "익선동 한옥거리"],
    period: "하루",
    time: "상시예약",
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/47.png",
    detailsub1: "한옥 골목과 국악 선율이 흐르는 서울 도심 속 전통 여행",
    detailsub2: "익선동과 돈화문 한옥길에서 조용한 한국의 미를 만나보세요.",
  },
  {
    id: 48,
    category: "tour",
    title: "도심 속 전통 한옥 체험",
    theme: ["역사", "힐링"],
    description: "한복 체험과 한옥·남산타워 전망까지 이어지는 서울 전통 투어",
    region: "서울시 중구",
    place: ["남산골 한옥마을", "남산서울타워"],
    period: "하루",
    time: "상시예약",
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/48.png",
    detailsub1: "남산 아래 고즈넉한 한옥마을에서 서울의 정취를 느껴보세요!",
    detailsub2: "한복 입고 남산타워까지, 사진도 추억도 가득한 전통 체험입니다.",
  },
  {
    id: 49,
    category: "tour",
    title: "가야의 시간, 김해 역사여행",
    theme: ["역사"],
    description: "가야문화 유물과 왕릉, 미술관·온천까지 함께하는 역사 여행",
    region: "경상남도 김해시",
    place: [
      "국립김해박물관",
      "김해 봉하마을",
      "수로왕릉",
      "김해 전통시장",
      "클레이아크김해미술관",
    ],
    period: "1박 2일",
    time: "상시예약",
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/49.png",
    detailsub1: "가야의 숨결과 김해의 전통을 만나는 역사 여행 1박 2일",
    detailsub2: "유적지부터 온천·미술관까지, 다양한 매력이 어우러집니다.",
  },
  {
    id: 50,
    category: "tour",
    title: "유네스코 마을, 경주의 숨결",
    theme: ["역사", "힐링"],
    description:
      "양반마을과 불국사, 보문호수까지 아우르는 경주의 깊은 역사 기행",
    region: "경상북도 경주시",
    place: [
      "양동마을",
      "월정교",
      "교촌마을",
      "황리단길",
      "불국사",
      "석굴암",
      "경주국립박물관",
      "동궁과 월지",
      "대릉원",
      "첨성대",
    ],
    period: "2박 3일",
    time: "상시예약",
    price: 10000,
    quantity: 1,
    img: "/images/tourclass/tourImg/50.png",
    detailsub1: "천년 고도 경주의 모든 것을 담은 유네스코 역사 기행",
    detailsub2:
      "불국사, 양동마을, 보문호수까지 2박 3일의 감동 여정을 만나보세요.",
  },
  {
    id: 51,
    category: "class",
    title: "나전칠기 손거울 책갈피 만들기",
    theme: ["만들기"],
    description: "반짝이는 자개로 전하는 감성 한 조각",
    region: "강원도 원주시",
    place: ["원주한지테마파크 1층 열린공간"],
    period: "2025.08.22 ~ 10.06",
    time: "120분",
    price: 30000,
    img: "/images/tourclass/classImg/51.png",
    quantity: 1,
    detailsub1: "섬세한 자개와 나전칠기의 아름다움을 직접 담아보는 시간",
    detailsub2:
      "책갈피와 손거울에 깃든 전통 공예의 반짝이는 감성을 선물하세요.",
  },
  {
    id: 52,
    category: "class",
    title: "[열공사포] 액막이 가죽 북어 만들기",
    theme: ["만들기"],
    description: "복을 부르고 액을 막는 귀여운 한 땀",
    region: "강원도 원주시",
    place: ["원주한지테마파크 1층 열린공간"],
    period: "2025.09.06 ~ 10.31",
    time: "120분",
    price: 30000,
    img: "/images/tourclass/classImg/52.png",
    quantity: 1,
    detailsub1:
      "행운을 부르는 귀여운 북어 인형, 가죽 공예로 직접 만들어보세요!",
    detailsub2: "전통과 유쾌함이 어우러진 힐링의 한 땀을 경험해요.",
  },
  {
    id: 53,
    category: "class",
    title: "한지, 다도명상을 만나다",
    theme: ["체험하기"],
    description: "고요한 쉼, 한지와 차에서 찾다",
    region: "강원도 원주시",
    place: ["원주한지테마파크 기획전시실1"],
    period: "2025.08.01 ~ 10.31",
    time: "90분",
    price: 20000,
    img: "/images/tourclass/classImg/53.png",
    quantity: 1,
    detailsub1: "고요한 찻잔과 한지의 향기로 몸과 마음을 쉬게 하는 명상 시간",
    detailsub2: "쉼과 집중, 자신에게 선물하는 온전한 순간을 만나보세요.",
  },
  {
    id: 54,
    category: "class",
    title: "화과자, 캐릭터송편만들기",
    theme: ["요리하기"],
    description: "눈과 입이 모두 즐거운 달콤한 시간",
    region: "경상북도 경주시",
    place: ["경주 교촌마을 내 떡인당"],
    period: "평일/주말 (수요일 휴무)",
    time: "90분",
    price: 15000,
    img: "/images/tourclass/classImg/54.png",
    quantity: 1,
    detailsub1: "알록달록 캐릭터 송편과 전통 화과자를 직접 만들어보는 시간",
    detailsub2: "아이부터 어른까지 달콤한 추억을 쌓는 오감만족 체험이에요.",
  },
  {
    id: 55,
    category: "class",
    title: "오곡면 만들기",
    theme: ["요리하기"],
    description: "곡물의 풍미를 담은 건강한 한 그릇",
    region: "경상북도 경주시",
    place: ["경주 교촌마을 내 교촌곳간"],
    period: "매주 화요일,수요일 휴무",
    time: "40분",
    price: 13000,
    img: "/images/tourclass/classImg/55.png",
    quantity: 1,
    detailsub1: "다섯 가지 곡물로 직접 반죽하고 뽑아내는 건강한 오곡면 만들기",
    detailsub2: "한 그릇에 담긴 정성과 자연의 풍미를 직접 느껴보세요.",
  },
  {
    id: 56,
    category: "class",
    title: "직접 만드는 도자기 클래스",
    theme: ["체험하기"],
    description: "물레 체험, 핸드빌딩, 캐릭터 접시",
    region: "경상북도 경주시",
    place: ["경주 교촌마을 내 토기공방/토기가마"],
    period: "평일/주말 (수요일 휴무)",
    time: "90분",
    price: 35000,
    img: "/images/tourclass/classImg/56.png",
    quantity: 1,
    detailsub1: "물레 위에서 도는 흙, 손끝에서 피어나는 나만의 도자기",
    detailsub2: "도심 속에서 만나는 감성 도예 클래스에 참여해보세요.",
  },
  {
    id: 57,
    category: "class",
    title: "국궁체험",
    theme: ["체험하기"],
    description: "전통과 역사 속으로 들어가는 한 발",
    region: "경기도 수원시",
    place: ["수원화성 연무대 내 국궁체험장"],
    period: "평일/주말 (화요일 휴무)",
    time: "20분",
    price: 3000,
    img: "/images/tourclass/classImg/57.png",
    quantity: 1,
    detailsub1: "활시위를 당기며 옛 선비의 품격과 집중력을 체험하는 국궁 시간",
    detailsub2: "짧지만 강렬한 전통 속으로의 여행, 수원화성에서 즐겨보세요.",
  },
  {
    id: 58,
    category: "class",
    title: "화성어차 타고 도는 수원화성",
    theme: ["체험하기"],
    description: "왕의 길 위에서 마주하는 수원의 풍경",
    region: "경기도 수원시",
    place: ["수원화성 연무대"],
    period: "평일/주말 (월요일 휴무)",
    time: "20분",
    price: 6000,
    img: "/images/tourclass/classImg/58.png",
    quantity: 1,
    detailsub1: "왕의 행차를 따라 도는 수원화성의 아름다운 풍경들",
    detailsub2: "화성어차를 타고 천천히 마주하는 고즈넉한 성곽의 정취.",
  },
  {
    id: 59,
    category: "class",
    title: "제30회 남한산성문화제\n떡메치기 체험",
    theme: ["체험하기"],
    description: "절구 소리에 담긴 조상의 손맛",
    region: "경기도 광주시",
    place: ["남한산성 도립공원 내 전통공원"],
    period: "2025.09.19 ~ 10.31",
    time: "60분",
    price: 5000,
    img: "/images/tourclass/classImg/59.png",
    quantity: 1,
    detailsub1: "절구질로 만들어보는 찰떡, 조상들의 손맛을 느껴보는 체험",
    detailsub2: "가족과 함께 힘차게 떡메치며 전통의 흥을 즐겨보세요.",
  },
  {
    id: 60,
    category: "class",
    title: "제30회 남한산성문화제\n선비·다례 체험",
    theme: ["체험하기"],
    description: "고즈넉한 과거 속 여유를 체험하는 시간",
    region: "경기도 광주시",
    place: ["남한산성 도립공원 내 광주문화원/다락원"],
    period: "2025.09.19 ~ 10.31",
    time: "40분",
    price: 10000,
    img: "/images/tourclass/classImg/60.png",
    quantity: 1,
    detailsub1: "선비 정신과 차의 예법을 직접 체험하는 고요한 전통의 시간",
    detailsub2:
      "다례로 배우는 한국의 품격과 여유, 과거로 떠나는 마음여행입니다.",
  },
  {
    id: 61,
    category: "class",
    title: "민화그리기",
    theme: ["체험하기"],
    description: "박물관에서 만나는 전통의 결",
    region: "전라북도 전주시",
    place: ["국립전주박물관 세미나실"],
    period: "평일/주말 (공휴일 휴무)",
    time: "60분",
    price: 15000,
    img: "/images/tourclass/classImg/61.png",
    quantity: 1,
    detailsub1: "전통 민화의 색과 이야기를 따라 한 장을 완성해보는 시간",
    detailsub2: "박물관 속 고요함에서 나만의 민화를 그려보세요.",
  },
  {
    id: 62,
    category: "class",
    title: "전통쟁반만들기",
    theme: ["만들기"],
    description: "전통을 담아내는 나만의 쟁반",
    region: "전라북도 전주시",
    place: ["국립전주박물관 세미나실"],
    period: "평일/주말 (공휴일 휴무)",
    time: "90분",
    price: 25000,
    img: "/images/tourclass/classImg/62.png",
    quantity: 1,
    detailsub1: "정성과 전통을 담아 만드는 나만의 쟁반 한 점",
    detailsub2: "실용성과 멋을 함께 담은 전통 공예를 체험해보세요.",
  },
  {
    id: 63,
    category: "class",
    title: "추사그림 따라그리기",
    theme: ["체험하기"],
    description: "옛 선비의 붓끝을 따라 한 획",
    region: "경기도 과천시",
    place: ["과천 추사박물관 체험실"],
    period: "평일/주말 (월요일 휴무)",
    time: "20분",
    price: 2000,
    img: "/images/tourclass/classImg/63.png",
    quantity: 1,
    detailsub1: "추사의 정신을 따라 붓끝으로 전통을 그리는 짧고 진한 체험",
    detailsub2: "한 획 한 획, 옛 선비의 마음을 느껴보세요.",
  },
  {
    id: 64,
    category: "class",
    title: "서예체험",
    theme: ["체험하기"],
    description: "먹향 따라 번지는 마음의 여백",
    region: "경기도 과천시",
    place: ["과천 추사박물관 체험실"],
    period: "평일/주말 (월요일 휴무)",
    time: "50분",
    price: 5000,
    img: "/images/tourclass/classImg/64.png",
    quantity: 1,
    detailsub1: "먹향과 함께 번져가는 선, 마음을 담아 적는 서예 한 줄",
    detailsub2: "고요한 집중 속에서 글씨에 내 마음을 담아보세요.",
  },
  {
    id: 65,
    category: "class",
    title: "2025하회, 선유줄불놀이",
    theme: ["체험하기"],
    description: "강 위를 수놓는 불의 예술, 하회의 밤",
    region: "경상북도 안동시",
    place: ["안동하회마을 낙동강변 일원"],
    period: "2025.08.14 ~ 11.08",
    time: "120분",
    price: 10000,
    img: "/images/tourclass/classImg/65.png",
    quantity: 1,
    detailsub1: "강 위로 펼쳐지는 불빛의 장관, 하회마을의 특별한 밤 체험",
    detailsub2: "선유줄불놀이와 함께하는 전통과 감동의 순간을 경험해보세요.",
  },
  {
    id: 66,
    category: "class",
    title: "호신팔찌 만들기",
    theme: ["만들기"],
    description: "한 땀 한 땀 엮어내는 나만의 수호 부적",
    region: "경기도 용인시",
    place: ["한국민속촌 내 상설체험장"],
    period: "금, 토, 일 및 공휴일",
    time: "60분",
    price: 15000,
    img: "/images/tourclass/classImg/66.png",
    quantity: 1,
    detailsub1: "정성을 담아 엮어내는 나만의 수호팔찌 만들기",
    detailsub2: "고운 실과 바람이 엮인, 전통 속의 의미 있는 공예 체험이에요.",
  },
  {
    id: 67,
    category: "class",
    title: "금줄놀이",
    theme: ["체험하기"],
    description: "금지된 장소까지 방울이 울리지 않게 지나가라",
    region: "경기도 용인시",
    place: ["한국민속촌 내 상설체험장"],
    period: "금, 토, 일 및 공휴일",
    time: "15분",
    price: 5000,
    img: "/images/tourclass/classImg/67.png",
    quantity: 1,
    detailsub1: "방울 소리를 울리지 않고 미션을 완수하라!",
    detailsub2: "웃음과 전통이 어우러진 짧고 짜릿한 놀이 체험이에요.",
  },
  {
    id: 68,
    category: "class",
    title: "막걸리: 한국 전통주 만들기 클래스",
    theme: ["요리하기"],
    description: "누룩 향 따라 빚는 나만의 막걸리",
    region: "서울시 강남구",
    place: ["시사쿡 컬리너리 아카데미"],
    period: "평일 (주말 및 공휴일 휴무)",
    time: "90분",
    price: 50000,
    img: "/images/tourclass/classImg/68.png",
    quantity: 1,
    detailsub1: "누룩과 쌀, 시간의 정성이 어우러진 나만의 막걸리 양조",
    detailsub2: "전통의 맛과 멋을 내 손으로 직접 빚어보세요.",
  },
  {
    id: 69,
    category: "class",
    title: "전통 막걸리 양조장\n투어 & 시음 체험",
    theme: ["체험하기"],
    description: "오래된 술의 깊은 맛과 이야기를 만나다",
    region: "서울시 중구",
    place: ["스프링 브리즈 양조장"],
    period: "매주 목, 금, 토",
    time: "90분",
    price: 30000,
    img: "/images/tourclass/classImg/69.png",
    quantity: 1,
    detailsub1: "도심 속 양조장에서 만나는 전통 술의 깊은 향기",
    detailsub2: "막걸리의 탄생과 이야기를 함께 음미하는 투어 체험이에요.",
  },
  {
    id: 70,
    category: "class",
    title: "전통 매듭 팔찌 만들기",
    theme: ["만들기"],
    description: "손끝으로 엮는 아름다운 전통의 매듭",
    region: "서울시 종로구",
    place: ["전통 공예관"],
    period: "매주 주말 및 공휴일",
    time: "60분",
    price: 20000,
    img: "/images/tourclass/classImg/70.png",
    quantity: 1,
    detailsub1: "섬세한 손끝으로 엮어내는 전통 매듭의 아름다움",
    detailsub2: "팔찌 하나에도 담긴 오래된 지혜와 감성을 느껴보세요.",
  },
  {
    id: 71,
    category: "class",
    title: "김치 담그기 클래스",
    theme: ["요리하기"],
    description: "전통 맛 그대로, 김치 담그기 체험",
    region: "전라북도 익산시",
    place: ["전통 음식 체험관"],
    period: "매주 토, 일",
    time: "90분",
    price: 25000,
    img: "/images/tourclass/classImg/71.png",
    quantity: 1,
    detailsub1: "김치 본연의 깊은 맛을 직접 담가보는 전통 요리 체험",
    detailsub2: "익산 전통 음식 체험관에서 가족과 함께 즐겨보세요.",
  },
  {
    id: 72,
    category: "class",
    title: "전통 한과 만들기",
    theme: ["요리하기"],
    description: "달콤한 한과를 직접 만들어보는 시간",
    region: "충청남도 공주시",
    place: ["한과 공방"],
    period: "평일/주말(월요일 휴무)",
    time: "60분",
    price: 30000,
    img: "/images/tourclass/classImg/72.png",
    quantity: 1,
    detailsub1: "달콤하고 고소한 전통 한과, 손끝에서 완성되는 맛의 예술",
    detailsub2: "공주 한과 공방에서 특별한 달콤함을 만들어보세요.",
  },
  {
    id: 73,
    category: "class",
    title: "전통 부채 만들기",
    theme: ["체험하기"],
    description: "전통 미를 담아 직접 만드는 부채",
    region: "서울시 종로구",
    place: ["공예 체험관"],
    period: "매주 주말 및 공휴일",
    time: "60분",
    price: 15000,
    img: "/images/tourclass/classImg/73.png",
    quantity: 1,
    detailsub1: "고운 전통 무늬와 색을 담아 직접 만드는 부채 만들기 체험",
    detailsub2: "종로 공예 체험관에서 나만의 부채를 완성해보세요.",
  },
  {
    id: 74,
    category: "class",
    title: "전통 연 만들기",
    theme: ["체험하기"],
    description: "하늘을 나는 우리 전통 연을 만들어보자",
    region: "경기도 파주시",
    place: ["연 공방"],
    period: "평일/주말 (화요일 휴무)",
    time: "60분",
    price: 12000,
    img: "/images/tourclass/classImg/74.png",
    quantity: 1,
    detailsub1: "하늘을 나는 우리 전통 연, 직접 만들고 즐기는 시간",
    detailsub2: "파주 연 공방에서 바람과 함께 전통을 느껴보세요.",
  },
  {
    id: 75,
    category: "class",
    title: "전통 장 담그기 체험",
    theme: ["체험하기"],
    description: "맛과 정성을 담아 우리 장을 만들어보자",
    region: "경기도 이천시",
    place: ["장 담그기 체험관"],
    period: "매주 일요일",
    time: "120분",
    price: 35000,
    img: "/images/tourclass/classImg/75.png",
    quantity: 1,
    detailsub1: "정성 가득 담긴 우리 장, 직접 담가보는 전통 발효 체험",
    detailsub2: "이천 장 담그기 체험관에서 깊은 맛을 완성하세요.",
  },
  {
    id: 76,
    category: "class",
    title: "한지 서책 만들기",
    theme: ["만들기"],
    description: "전통 한지를 엮어 만드는 손수 책 체험",
    region: "전라북도 완주군",
    place: ["완주 대승한지마을"],
    period: "평일/주말 (월요일 휴무)",
    time: "50분",
    price: 8000,
    img: "/images/tourclass/classImg/76.png",
    quantity: 1,
    detailsub1: "한지로 엮어 만드는 나만의 서책, 손맛과 전통의 만남",
    detailsub2: "완주 대승한지마을에서 특별한 공예 시간을 가져보세요.",
  },
  {
    id: 77,
    category: "class",
    title: "한지사 천연염색 에코 스카프",
    theme: ["만들기"],
    description: "자연의 색을 머금은 한지사로 완성한 친환경 스카프",
    region: "전라북도 완주군",
    place: ["완주 대승한지마을"],
    period: "평일/주말 (월요일 휴무)",
    time: "70분",
    price: 80000,
    img: "/images/tourclass/classImg/77.png",
    quantity: 1,
    detailsub1: "자연 염색의 빛깔을 머금은 친환경 한지사 스카프 만들기",
    detailsub2: "완주 한지마을에서 환경과 전통을 함께 체험해요.",
  },
  {
    id: 78,
    category: "class",
    title: "한지 원형 소품함 만들기",
    theme: ["만들기"],
    description: "전통 한지로 빚어내는 나만의 원형 소품함 제작",
    region: "전라북도 완주군",
    place: ["완주 대승한지마을"],
    period: "평일/주말 (월요일 휴무)",
    time: "60분",
    price: 15000,
    img: "/images/tourclass/classImg/78.png",
    quantity: 1,
    detailsub1: "전통 한지로 만드는 소품함, 실용성과 아름다움의 조화",
    detailsub2: "완주 대승한지마을에서 나만의 특별한 작품을 완성하세요.",
  },
  {
    id: 79,
    category: "class",
    title: "아홉칸의 멋, 구절판 만들기",
    theme: ["요리하기"],
    description: "아홉 칸에 담긴 전통의 맛과 멋을 직접 완성하는 체험",
    region: "전라북도 전주시",
    place: ["전주 한국전통문화전당"],
    period: "평일/주말 (화요일 휴무)",
    time: "90분",
    price: 20000,
    img: "/images/tourclass/classImg/79.png",
    quantity: 1,
    detailsub1: "아홉 칸에 담긴 전통의 맛과 멋, 직접 완성하는 구절판 체험",
    detailsub2: "전주 한국전통문화전당에서 전통 음식의 진수를 느껴보세요.",
  },
  {
    id: 80,
    category: "class",
    title: "바삭한 전통, 쌀강정 만들기",
    theme: ["요리하기"],
    description: "고소한 쌀과 달콤한 조청으로 완성하는 우리 전통 간식",
    region: "전라북도 전주시",
    place: ["전주 한국전통문화전당"],
    period: "평일/주말 (화요일 휴무)",
    time: "60분",
    price: 13000,
    img: "/images/tourclass/classImg/80.png",
    quantity: 1,
    detailsub1: "고소하고 바삭한 전통 간식, 쌀강정을 직접 만들어보는 시간",
    detailsub2: "전주 전통문화전당에서 달콤한 추억을 만들어보세요.",
  },
  {
    id: 81,
    category: "class",
    title: "궁중의 맛, 떡볶이 만들기",
    theme: ["요리하기"],
    description: "궁중에서 즐기던 간장 양념 떡볶이 체험",
    region: "전라북도 전주시",
    place: ["전주 한국전통문화전당"],
    period: "평일/주말 (수요일 휴무)",
    time: "60분",
    price: 15000,
    img: "/images/tourclass/classImg/81.png",
    quantity: 1,
    detailsub1: "궁중 간장 양념으로 맛을 낸 떡볶이, 전통의 맛을 체험해보세요!",
    detailsub2: "전주 한국전통문화전당에서 특별한 요리 시간을 가져보세요.",
  },
  {
    id: 82,
    category: "class",
    title: "예와 멋의 길, 전통혼례 체험",
    theme: ["체험하기"],
    description: "우리 문화유산 속 혼례 예법과 아름다움을 직접 경험하는 시간",
    region: "경상북도 안동시",
    place: ["안동하회마을"],
    period: "4월~11월, 월요일 휴무",
    time: "90분",
    price: 50000,
    img: "/images/tourclass/classImg/82.png",
    quantity: 1,
    detailsub1:
      "전통 혼례 예법과 멋을 직접 체험하며 우리 문화의 깊이를 느껴보세요!",
    detailsub2: "안동 하회마을에서 아름다운 혼례의 순간을 경험할 수 있습니다.",
  },
  {
    id: 83,
    category: "class",
    title: "마음을 새기는 글,\n가훈 쓰기 체험",
    theme: ["체험하기"],
    description: "문서예로 전통의 멋과 가문의 정신을 담아내는 경험",
    region: "경상북도 안동시",
    place: ["안동하회마을 內 하중재"],
    period: "4월~종료일 까지, 평일 휴무",
    time: "50분",
    price: 15000,
    img: "/images/tourclass/classImg/83.png",
    quantity: 1,
    detailsub1: "전통 문서예로 가훈을 쓰며 가문의 정신과 멋을 새겨보는 시간",
    detailsub2: "안동 하회마을 하중재에서 전통 글쓰기의 진수를 체험하세요.",
  },
  {
    id: 84,
    category: "class",
    title: "손끝에 깃든 전통, 짚공예 체험",
    theme: ["체험하기"],
    description: "문화유산인 짚으로 생활 소품을 빚어내는 시간",
    region: "경상북도 안동시",
    place: ["안동하회마을 內 남촌댁(염행당)"],
    period: "4월~종료일 까지, 평일 휴무",
    time: "70분",
    price: 25000,
    img: "/images/tourclass/classImg/84.png",
    quantity: 1,
    detailsub1: "짚으로 만드는 생활 소품, 손끝에서 빚어내는 전통 공예의 매력",
    detailsub2: "안동 하회마을 남촌댁에서 문화유산의 숨결을 느껴보세요.",
  },
  {
    id: 85,
    category: "class",
    title: "망치로 그려내는 전통금속공예",
    theme: ["만들기"],
    description: "두드림으로 완성하는 전통의 아름다움",
    region: "서울시 중구",
    place: ["남산골한옥마을 옥인동 가옥"],
    period: "4월~10월, 매주 금,토,일",
    time: "50분",
    price: 15000,
    img: "/images/tourclass/classImg/85.png",
    quantity: 1,
    detailsub1: "망치로 두드려 완성하는 전통 금속공예, 예술의 장을 경험하세요!",
    detailsub2:
      "서울 남산골한옥마을 옥인동 가옥에서 전통 공예의 매력을 만끽하세요.",
  },
  {
    id: 86,
    category: "class",
    title: "천연자개로 직접 만드는 나만의 공예 작품",
    theme: ["만들기"],
    description: "자개 빛깔로 완성하는 나만의 전통 작품",
    region: "서울시 중구",
    place: ["남산골한옥마을 김춘영 가옥"],
    period: "4월~10월, 매주 금,토,일",
    time: "50분",
    price: 25000,
    img: "/images/tourclass/classImg/86.png",
    quantity: 1,
    detailsub1: "천연 자개의 빛깔로 완성하는 나만의 전통 공예 작품 만들기",
    detailsub2:
      "서울 남산골한옥마을 김춘영 가옥에서 특별한 공예 체험을 즐기세요.",
  },
  {
    id: 87,
    category: "class",
    title: "남산골 한옥콘서트 <취향>",
    theme: ["체험하기"],
    description: "한옥의 운치 속에서 즐기는 전통과 현대의 선율",
    region: "서울시 중구",
    place: ["남산골한옥마을 관훈동 민씨 가옥"],
    period: "9월~11월, 매주 금요일",
    time: "90분",
    price: 30000,
    img: "/images/tourclass/classImg/87.png",
    quantity: 1,
    detailsub1:
      "한옥의 운치 속에서 전통과 현대가 어우러진 음악 선율을 감상하세요.",
    detailsub2:
      "남산골한옥마을 관훈동 민씨 가옥에서 잊지 못할 콘서트를 경험해보세요!",
  },
  {
    id: 88,
    category: "class",
    title: "옷에 담긴 우리 멋, 한복 체험",
    theme: ["체험하기"],
    description: "고운 색과 곡선으로 빚어진 전통의 품격을 입어보는 경험",
    region: "서울시 종로구",
    place: ["지지배배한복"],
    period: "평일/주말 (월요일 휴무)",
    time: "120분",
    price: 30000,
    img: "/images/tourclass/classImg/88.png",
    quantity: 1,
    detailsub1: "고운 색과 우아한 곡선의 전통 한복, 직접 입어보는 특별한 체험",
    detailsub2: "종로 지지배배한복에서 우리 옷의 멋과 품격을 느껴보세요.",
  },
  {
    id: 89,
    category: "class",
    title: "다예원, 다도체험",
    theme: ["체험하기"],
    description: "차 향기 가득한 곳에서 전통 다도를 체험하는 공간",
    region: "전라남도 장흥군",
    place: ["장흥 다예원"],
    period: "매주 화, 수요일",
    time: "90분",
    price: 25000,
    img: "/images/tourclass/classImg/89.png",
    quantity: 1,
    detailsub1: "차 향기 가득한 공간에서 전통 다도 문화를 깊이 체험해보세요.",
    detailsub2: "장흥 다예원에서 차와 함께하는 여유로운 시간을 즐기세요!",
  },
  {
    id: 90,
    category: "class",
    title: "다채로운 도자기 체험",
    theme: ["체험하기"],
    description: "전통과 예술이 살아 숨 쉬는 공간",
    region: "경기도 이천시",
    place: ["사기막골도예촌"],
    period: "평일/주말 (월요일 휴무)",
    time: "90분",
    price: 45000,
    img: "/images/tourclass/classImg/90.png",
    quantity: 1,
    detailsub1:
      "전통과 예술이 숨 쉬는 도자기 체험, 나만의 작품을 완성해보세요!",
    detailsub2:
      "경기도 이천 사기막골도예촌에서 특별한 도자기 공예 시간을 가져보세요.",
  },
  {
    id: 91,
    category: "class",
    title: "전통 놀이 체험마당",
    theme: ["체험하기"],
    description: "우리 문화유산 속 놀이를 즐기며 함께 어울리는 시간",
    region: "대전광역시",
    place: ["대전 유천동 현장지원센터"],
    period: "매주 화요일 오후 2시",
    time: "60분",
    price: 5000,
    img: "/images/tourclass/classImg/91.png",
    quantity: 1,
    detailsub1: "전통 놀이를 즐기며 모두가 함께 어울리는 따뜻한 시간",
    detailsub2: "대전 유천동 현장지원센터에서 매주 화요일 오후 2시에 만나요.",
  },
  {
    id: 92,
    category: "class",
    title: "전통주 체험하기",
    theme: ["체험하기"],
    description: "변하지 않는 전통의 가치, 전통주",
    region: "서울시 종로구",
    place: ["한식문화공간 전통주갤러리"],
    period: "화요일~일요일, 월요일 휴관",
    time: "60분",
    price: 10000,
    img: "/images/tourclass/classImg/92.png",
    quantity: 1,
    detailsub1: "전통주의 깊은 맛과 가치를 직접 체험하며 느껴보세요!",
    detailsub2: "서울 종로구 한식문화공간 전통주갤러리에서 진행됩니다.",
  },
  {
    id: 93,
    category: "class",
    title: "락고재 컬쳐 라운지 애가헌",
    theme: ["체험하기"],
    description: "한옥의 품격 속에서 문화와 예술을 함께 즐기는 공간",
    region: "서울시 종로구",
    place: ["서울시 종로구 애가헌"],
    period: "수요일~일요일",
    time: "150분",
    price: 45000,
    img: "/images/tourclass/classImg/93.png",
    quantity: 1,
    detailsub1: "한옥의 품격 속에서 문화와 예술을 만끽할 수 있는 공간",
    detailsub2: "서울 종로구 애가헌에서 수~일요일 특별한 시간을 즐기세요.",
  },
  {
    id: 94,
    category: "class",
    title: "전통 신 체험",
    theme: ["체험하기"],
    description: "옛 멋을 담은 전통 신을 직접 신어보는 경험",
    region: "부산광역시 사하구",
    place: ["전통신전수관"],
    period: "평일/주말 (공휴일 휴무)",
    time: "60",
    price: 50000,
    img: "/images/tourclass/classImg/94.png",
    quantity: 1,
    detailsub1: "전통 신을 직접 신어보며 옛 멋과 정취를 체험해보세요!",
    detailsub2: "부산 사하구 전통신전수관에서 전통을 느낄 수 있습니다.",
  },
  {
    id: 95,
    category: "class",
    title: "수영전통달집놀이",
    theme: ["체험하기"],
    description: "전통문화 및 전승의 장 체험",
    region: "부산광역시 수영구",
    place: ["부산광역시 수영구 광안리해변"],
    period: "2월 12일",
    time: "70분",
    price: 2000,
    img: "/images/tourclass/classImg/95.png",
    quantity: 1,
    detailsub1: "부산 광안리해변에서 전통 달집놀이로 문화와 역사를 만나요!",
    detailsub2: "매년 2월 12일, 특별한 전통문화 체험의 장입니다.",
  },
  {
    id: 96,
    category: "class",
    title: "안성 남사당놀이 공연",
    theme: ["체험하기"],
    description: "천년의 흥과 신명이 살아있는 전통 연희를 즐기는 시간",
    region: "경기도 안성시",
    place: ["안성 남사당 공연장 "],
    period: "4월~11월, 매주 주말",
    time: "80분",
    price: 12000,
    img: "/images/tourclass/classImg/96.png",
    quantity: 1,
    detailsub1: "천년의 흥과 신명이 살아있는 안성 남사당놀이 공연",
    detailsub2: "4월부터 11월까지 매주 주말 안성 공연장에서 즐기세요.",
  },
  {
    id: 97,
    category: "class",
    title: "진주 무형문화재 공연",
    theme: ["체험하기"],
    description: "진주성에서 펼쳐지는 국가무형문화재의 흥겨운 무대",
    region: "경상남도 진주시",
    place: ["진주성(야외공연장, 촉석루)"],
    period: "매주 토요일 오후",
    time: "90분",
    price: 5000,
    img: "/images/tourclass/classImg/97.png",
    quantity: 1,
    detailsub1: "진주성 야외공연장에서 펼쳐지는 무형문화재의 흥겨운 무대",
    detailsub2: "매주 토요일 오후에 즐기는 전통 문화 공연입니다.",
  },
  {
    id: 98,
    category: "class",
    title: "한국전통음식문화체험관",
    theme: ["체험하기"],
    description: "외국인 친구와 함께가면 더 좋은 평창의 핫플레이스",
    region: "강원도 평창군",
    place: ["정강원"],
    period: "매주 월요일 및 명절 휴무",
    time: "80분",
    price: 25000,
    img: "/images/tourclass/classImg/98.png",
    quantity: 1,
    detailsub1: "외국인 친구와 함께 가면 더 좋은 평창의 전통 음식 체험관",
    detailsub2: "정강원에서 전통음식과 문화를 경험해보세요.",
  },
  {
    id: 99,
    category: "class",
    title: "오대산 자연명상마을",
    theme: ["체험하기"],
    description: "휴식과 치유를 누리는 힐링 한옥 체험",
    region: "강원도 평창군",
    place: ["월정사 인근 명상마을"],
    period: "평일/주말",
    time: "14시 입실, 11시 퇴실",
    price: 150000,
    img: "/images/tourclass/classImg/99.png",
    quantity: 1,
    detailsub1: "오대산 인근 자연명상마을에서 휴식과 치유를 누려보세요!",
    detailsub2: "평일과 주말 모두 이용 가능하며 힐링 한옥 체험입니다.",
  },
  {
    id: 100,
    category: "class",
    title: "고택문화체험관",
    theme: ["체험하기"],
    description: "선비문화와 지역적 특색이 공존하는 복합적 문화 관광",
    region: "전라북도 정읍시",
    place: ["정읍시 산외면 김동수씨 가옥 옆"],
    period: "연중무휴",
    time: "50분",
    price: 10000,
    img: "/images/tourclass/classImg/100.png",
    quantity: 1,
    detailsub1: "선비문화와 지역 특색이 어우러진 고택 문화체험의 기회!",
    detailsub2: "전라북도 정읍 산외면 김동수씨 가옥 옆에서 연중 무휴 운영",
  },
];
