export default [
  {
    id: 1,
    category: "tour",
    title: "경복궁 달빛기행",
    theme: [
      "역사",
      "예술"
    ],
    description: "경복궁 내 투어 및 공연관람",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "외소주방",
      "자경전&흥복전",
      "장고",
      "집옥재&팔우정",
      "건청궁",
      "향원정"
    ],
    price: 54000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 2,
    category: "tour",
    title: "남한산성 행궁의 역사산책",
    theme: [
      "힐링",
      "역사"
    ],
    description: "남한산성 투어 및 도예체험",
    period: "하루",
    time: "상시예약",
    region: "경기도 광주시",
    place: [
      "남한산성",
      "청와정 카페",
      "도자공방 오롯",
    ],
    price: 32000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 3,
    category: "tour",
    title: "익선동 한옥거리 미식 산책",
    theme: [
      "라이프"
    ],
    description: "전통, 모던 감성 섞인 한옥 데이트",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "익선동 골목길",
      "옛날 다방",
      "청계천"
    ],
    price: 10000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 4,
    category: "tour",
    title: "전통과 현대를 잇는 예술여행",
    theme: [
      "융합",
      "예술"
    ],
    description: "전통, 모던 감성의 미술관/박물관 투어",
    period: "1박 2일",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "서울공예박물관",
      "북촌 한옥마을",
      "국립현대미술관",
      "리움미술관",
      "서울시립미술관",
      "남산골 한옥마을",
    ],
    price: 100000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 5,
    category: "tour",
    title: "운현궁의 비밀스러운 하루",
    theme: [
      "역사",
      "라이프"
    ],
    description: "운현궁 투어 및 전통문화체험",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "운현궁",
      "인사동 거리",
      "쌈지길",
      "익선동 한옥거리"
    ],
    price: 56000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 6,
    category: "tour",
    title: "북촌 로맨스, K-드라마 속으로",
    theme: [
      "융합"
    ],
    description: "북촌 한옥마을 속 K-드라마 촬영지 투어",
    period: "하루",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "가회동 돌담길",
      "가회동 한옥체험관",
      "익선동 한옥거리"
    ],
    price: 66000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 7,
    category: "tour",
    title: "조선왕조 이야기, 궁궐을 걷다",
    theme: [
      "역사",
      "힐링"
    ],
    description: "종로구 궁궐 투어 및 한옥 홈스테이",
    period: "1박 2일",
    time: "상시예약",
    region: "서울시 종로구",
    place: [
      "경복궁",
      "국립민속박물관",
      "북촌 한옥마을",
      "덕수궁",
      "광화문",
      "서울역사박물관"
    ],
    price: 98000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 8,
    category: "tour",
    title: "천년의 숨결, 경주 전통기행",
    theme: [
      "라이프",
      "역사",
      "융합"
    ],
    description: "경주에서 즐기는 전통문화와 역사, 맛 여행",
    period: "2박 3일",
    time: "상시예약",
    region: "경상북도 경주시",
    place: [
      "경주 교촌한옥마을",
      "미경 전통식문화연구소",
      "경주 미정당",
      "한옥스테이",
      "국립경주박물관",
      "황리단길",
    ],
    price: 154000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 9,
    category: "tour",
    title: "수원 화성, 행궁동 골목길 시간 여행",
    theme: [
      "역사",
      "힐링"
    ],
    description: "수원 화성 투어",
    period: "하루",
    time: "상시예약",
    region: "경기도 수원시",
    place: [
      "화성행굴",
      "행궁동",
      "팔달문"
    ],
    price: 48000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 10,
    category: "tour",
    title: "파주, 예술이 피어나는 길",
    theme: [
      "예술",
      "힐링",
      "융합"
    ],
    description: "파주에서 느끼는 예술의 길",
    period: "1박 2일",
    time: "상시예약",
    region: "경기도 파주시",
    place: [
      "헤이리 예술마을",
      "뮤지엄 모아",
      "아트팩토리",
      "헤이리 골목",
      "파주출판도시",
      "임진각"
    ],
    price: 79000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 11,
    category: "tour",
    title: "빛과 자연의 원주",
    theme: [
      "힐링",
      "예술"
    ],
    description: "뮤지엄산 관람과 원주 대표 관광지 체험",
    period: "하루",
    time: "상시예약",
    region: "강원도 원주시",
    place: [
      "뮤지엄산",
      "소금산 출렁다리",
      "원주 중앙시장"
    ],
    price: 68000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 12,
    category: "tour",
    title: "소양강 위에서, 춘천의 시간",
    theme: [
      "힐링",
      "역사"
    ],
    description: "국립춘천박물관 관람과 호수 도시 춘천 체험",
    period: "하루",
    time: "상시예약",
    region: "강원도 춘천시",
    place: [
      "국립춘천박물관",
      "소양강 스카이워크",
      "애니메이션박물관"
    ],
    price: 58000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 13,
    category: "tour",
    title: "파도와 예술이 머무는 강릉 1박2일",
    theme: [
      "예술",
      "힐링"
    ],
    description: "강릉시립미술관 관람과 바다·전통·카페거리 체험",
    period: "1박 2일",
    time: "상시예약",
    region: "강원도 강릉시",
    place: [
      "강릉시립미술관",
      "강릉 오죽헌",
      "강릉 중앙시장",
      "경포호수",
      "선교장",
      "주문진 방파제"
    ],
    price: 99000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 14,
    category: "tour",
    title: "파도 따라 걷는 속초·양양 아트로드",
    theme: [
      "예술",
      "힐링"
    ],
    description: "동해안 박물관·미술관과 해변 감성 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "강원도 속초시",
    place: [
      "속초시립박물관",
      "속초 중앙시장",
      "청초호 호수공원",
      "일현미술관",
      "낙산사",
      "서피비치 카페거리"
    ],
    price: 110000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 15,
    category: "tour",
    title: "보은·청주, 전통과 예술이 만나는 여행",
    theme: [
      "예술",
      "역사"
    ],
    description: "속리산 법주사의 전통과 현대 예술을 잇는 문화여행.",
    period: "1박 2일",
    time: "상시예약",
    region: "충청북도 청주시",
    place: [
      "속리산 법주사",
      "상단산성",
      "육거리종합시장",
      "청주공예비엔날레",
      "청주시립미술관",
      "공예비엔날레"
    ],
    price: 96000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 16,
    category: "tour",
    title: "별빛과 역사가 머무는 영월 1박2일",
    theme: [
      "역사",
      "라이프"
    ],
    description: "전통 + 모던 감성 섞인 한옥 데이트",
    period: "1박 2일",
    time: "상시예약",
    region: "강원도 영월군",
    place: [
      "난고김삿갓문학관",
      "단종역사관",
      "동강사진박물관",
      "별마로천문대",
      "라디오스타박물관",
      "동강생태정보센터"
    ],
    price: 84000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 17,
    category: "tour",
    title: "문학과 자연이 흐르는 인제 하루",
    theme: [
      "예술"
    ],
    description: "서예·문학관람과 내설악 풍경 감상",
    period: "하루",
    time: "상시예약",
    region: "강원도 인제군",
    place: [
      "여초서예관",
      "내설악미술관",
      "백담사"
    ],
    price: 54000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 18,
    category: "tour",
    title: "백제의 고도 공주 여행",
    theme: [
      "역사"
    ],
    description: "백제의 고도 숨결이 흐르는 금강여행",
    period: "1박 2일",
    time: "상시예약",
    region: "충청남도 공주시",
    place: [
      "국립공주박물관",
      "무령왕릉",
      "공주 한옥마을",
      "공산성",
      "공주 시장",
      "금강변"
    ],
    price: 120000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 19,
    category: "tour",
    title: "청주 도심 문화 예술 하루여행",
    theme: [
      "예술",
      "힐링"
    ],
    description: "역사와 예술이 숨쉬는 청주의 예술여행",
    period: "하루",
    time: "상시예약",
    region: "충청북도 청주시",
    place: [
      "국립청주박물관",
      "청주 성안길",
      "청주공예비엔날레"
    ],
    price: 48000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 20,
    category: "tour",
    title: "백제 로맨스, 부여 1박 2일",
    theme: [
      "힐링",
      "융합"
    ],
    description: "여전히 아름다운 백제의 꽃, 숨은 핫플 여행",
    period: "1박 2일",
    time: "상시예약",
    region: "충청남도 부여군",
    place: [
      "국립부여박물관",
      "부소산성",
      "전통시장",
      "한옥길",
      "능산리 고군분",
      "백제왕릉원"
    ],
    price: 108000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 21,
    category: "tour",
    title: "현대예술과 청춘 감성 하루여행",
    theme: [
      "예술",
      "라이프"
    ],
    description: "미술관부터 공원 산책, 역사와 예술을 걷다",
    period: "하루",
    time: "상시예약",
    region: "충청북도 청주시",
    place: [
      "청주시립미술관",
      "문화예술창작촌",
      "청주 성안길"
    ],
    price: 60000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 22,
    category: "tour",
    title: "전통과 현대가 어우러진 용인 하루",
    theme: [
      "라이프"
    ],
    description: "한국민속촌 체험과 용인 대표 명소 탐방",
    period: "하루",
    time: "상시예약",
    region: "경기도 용인시",
    place: [
      "한국민속촌",
      "에버랜드",
      "호암미술관"
    ],
    price: 58000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 23,
    category: "tour",
    title: "호수와 예술이 머무는 안산 하루",
    theme: [
      "예술",
      "힐링"
    ],
    description: "경기도미술관 관람과 호수·바다 감성 여행",
    period: "하루",
    time: "상시예약",
    region: "경기도 안산시",
    place: [
      "경기도미술관",
      "안산호수공원",
      "안산갈대습지공원"
    ],
    price: 48000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 24,
    category: "tour",
    title: "송도, 전통과 미래가 만나는 길",
    theme: [
      "라이프"
    ],
    description: "송도 한옥마을과 송도 국제도시 체험",
    period: "하루",
    time: "상시예약",
    region: "인천 연수구",
    place: [
      "송도 한옥마을",
      "송도 센트럴파크",
      "G타워 전망대"
    ],
    price: 51000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
  {
    id: 25,
    category: "tour",
    title: "한국 전통의 모든 것, 국립중앙박물관 스탬프투어",
    theme: [
      "역사",
      "예술"
    ],
    description: "스탬프 투어와 전통을 통한 한국의 역사와 문화 체험",
    period: "하루",
    time: "상시예약",
    region: "서울 용산구",
    place: [
      "국립중앙박물관",
      "한국관",
      "불교미술관"
    ],
    price: 38000,
    quantity: 1,
    img: "/images/tour/xx.png"
  },
    {
      id: 26,
      category: "tour",
      title: "현대미술과 도심 속 감각적인 하루",
      theme: [
        "예술","라이프"
      ],
      description: "현대미술 전시와 덕수궁 돌담길, 도심 문화 체험",
      period: "하루",
      time: "상시예약",
      region: "서울시 종로구",
      place: [
        "국립현대미술관",
        "덕수궁 돌담길",
        "서울시립미술관",
        "정동극장"
      ],
      price: 10000,
      quantity: 1,
        
      img: "/images/tour/xx.png"
    },
    {
      id: 27,
      category: "tour",
      title: "역사의 숨결, 나주 하루",
      theme: [
        "역사"
      ],
      description: "국립나주박물관 관람과 나주 고대 역사 탐방",
      period: "하루",
      time: "상시예약",
      region: "전라남도 나주시",
      place: [
        "국립나주박물관",
        "나주읍성",
        "금성관",
        "빛가람 혁신도시 카페거리",
      ],
      price: 10000,
      quantity: 1,
        
      img: "/images/tour/xx.png"
    },
    {
      id: 28,
      category: "tour",
      title: "백제의 기억, 익산 하루",
      theme: [
        "역사"
      ],
      description: "국립익산박물관과 미륵사지 탐방",
      period: "하루",
      time: "상시예약",
      region: "전라북도 익산시",
      place: [
        "국립익산박물관",
        "미륵사지",
        "왕궁리 유적",
      ],
      price: 10000,
      quantity: 1,
        
      img: "/images/tour/xx.png"
    },
    {
      id: 29,
      category: "tour",
      title: "예술과 자연의 조화, 완주 하루",
      theme: [
        "예술"
      ],
      description: "전북도립미술관과 예술촌 탐방",
      period: "하루",
      time: "상시예약",
      region: "전라북도 완주군",
      place: [
        "전북도립미술관",
        "삼례문화예술촌",
        "대둔산",
      ],
      price: 10000,
      quantity: 1,
        
      img: "/images/tour/xx.png"
    },
    {
      id: 30,
      category: "tour",
      title: "시간이 머무는 길, 전주 1박2일",
      theme: [
        "역사",
        "라이프"
      ],
      description: "전주 한옥마을과 경기전, 전통음식 투어",
      period: "1박 2일",
      time: "상시예약",
      region: "전라북도 전주시",
      place: [
        "전주 경기전",
        "전주 한옥마을",
        "국립전주박물관",
        "향교길",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 31,
      category: "tour",
      title: "예술의 파동, 광주에서 시작되다",
      theme: [
        "예술",
        "융합",
      ],
      description: "국립광주박물관, 아시아문화전당, 광주비엔날레 포함 예술·역사 투어",
      period: "2박 3일",
      time: "상시예약",
      region: "광주",
      place: [
        "국립광주박물관",
        "펭귄마을",
        "무등산 자락 카페",
        "국립아시아문화전당",
        "양림동 역사문화마을",
        "광주시립미술관",
        "광주비엔날레",
        "5·18기념관",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 32,
      category: "tour",
      title: "남강의 등불, 진주 역사 하루여행",
      theme: [
        "역사",
        "힐링",
      ],
      description: "역사와 전통을 담은 국립진주박물관 관람과 남강 야경으로 즐기는 진주 하루 여행",
      period: "하루",
      time: "상시예약",
      region: "경상남도 진주시",
      place: [
        "국립진주박물관",
        "촉석루",
        "진주남강유등전 기념 전시관",
        "남강 중앙시장"
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 33,
      category: "tour",
      title: "대구의 시간, 신라에서 근대까지",
      theme: [
        "역사",
        "라이프"
      ],
      description: "역사와 예술, 김광석 거리와 팔공산을 즐기는 대구 1박 2일 여행",
      period: "1박 2일",
      time: "상시예약",
      region: "대구",
      place: [
        "국립대구박물관",
        "근대문화골목",
        "김광석 다시그리기길",
        "팔공산 동화사",
        "대구 수성못 카페거리"
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 34,
      category: "tour",
      title: "하회마을, 탈춤과 풍류의 길",
      theme: [
        "역사",
        "힐링"
      ],
      description: "전통 한옥과 탈춤, 유네스코 서원과 월영교를 즐기는 안동 1박 2일 여행",
      period: "1박 2일",
      time: "상시예약",
      region: "경상북도 안동시",
      place: [
        "안동 하회마을",
        "병산서원",
        "월영교",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 35,
      category: "tour",
      title: "바다 위의 예술, 부산비엔날레 하루",
      theme: [
        "예술",
        "라이프"
      ],
      description: "현대미술과 역사, 해변 노을을 즐기는 부산 하루 여행",
      period: "하루",
      time: "상시예약",
      region: "부산",
      place: [
        "부산비엔날레",
        "남포동 카페거리",
        "부산근현대역사관",
        "광안리 해변",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 36,
      category: "tour",
      title: "철길 위의 예술, F1963 투어",
      theme: [
        "예술",
        "융합"
      ],
      description: "예술 전시장과 감각적인 카페 거리, 야경을 즐기는 부산 하루 여행",
      period: "하루",
      time: "상시예약",
      region: "부산",
      place: [
        "F1963",
        "수영강 카페거리",
        "망미동 카페거리",
        "센텀시티 영화의 전당",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 37,
      category: "tour",
      title: "미래를 그리는 도시, 울산 예술여행",
      theme: [
        "예술",
        "힐링"
      ],
      description: "미디어아트와 고래문화, 태화강 야경과 간절곶 일출을 즐기는 울산 1박 2일 여행",
      period: "1박 2일",
      time: "상시예약",
      region: "울산",
      place: [
        "울산시립미술관",
        "울산 중앙시장",
        "장생포 고래문화마을",
        "태화강 국가정원",
        "간절곶",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 38,
      category: "tour",
      title: "개실마을, 느린 발걸음의 하루",
      theme: [
        "역사",
        "힐링"
      ],
      description: "전통 한옥과 대가야 역사, 강변 산책을 즐기는 고령 하루 여행",
      period: "하루",
      time: "상시예약",
      region: "경상북도 고령군",
      place: [
        "고령 개실마을",
        "대가야 역사테마관광지",
        "낙동강"
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 39,
      category: "tour",
      title: "한글에서 한옥까지: 오감으로 즐기는 한국문화 하루여행",
      theme: [
        "역사",
        "힐링"
      ],
      description: "국립한글박물관에서 시작해 전통음식·공예·한옥길까지 한국의 멋을 오롯이 체험하는 하루 투어",
      period: "하루",
      time: "상시예약",
      region: "서울시 용산구",
      place: [
        "국립한글박물관",
        "경복궁",
        "인사동",
        "북촌 한옥마을",
        "청계천",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 40,
      category: "tour",
      title: "놀며 배우는 한국문화 하루여행: 어린이 민속 체험 투어",
      theme: [
        "역사",
        "융합"
      ],
      description: "국립민속박물관 어린이박물관에서 시작해 전통놀이·공예·간식까지 즐기는 어린이 맞춤 한국문화 체험",
      period: "하루",
      time: "상시예약",
      region: "서울시 종로구",
      place: [
        "국립민속박물관 어린이박물관",
        "북촌 한옥마을",
        "인사동 전통문화거리",
        "청계천",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 41,
      category: "tour",
      title: "예술과 한옥정원, 그리고 손끝 체험: 석파정 한국문화 1박 2일",
      theme: [
        "예술",
        "융합",
      ],
      description: "석파정 서울미술관과 전통 정원, 북촌 공예체험과 고궁 산책까지 세대별로 즐기는 한국문화 종합 투어",
      period: "하루",
      time: "상시예약",
      region: "서울시 종로구",
      place: [
        "석파정 서울미술관",
        "북촌 한옥마을",
        "인사동 전통문화거리",
        "경복궁",
        "광화문 전통시장",
        "국립민속박물관",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 42,
      category: "tour",
      title: "바다와 예술의 만남, 부산 아트 데이",
      theme: [
        "예술",
        "라이프"
      ],
      description: "현대미술과 광안리 바다 풍경을 함께 즐기는 하루 예술 산책",
      period: "하루",
      time: "상시예약",
      region: "부산",
      place: [
        "부산시립미술관",
        "영화의 전당",
        "광안리 해변",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 43,
      category: "tour",
      title: "대구, 예술의 빛과 근대의 길",
      theme: [
        "역사",
        "예술"
      ],
      description: "미술 전시와 근대골목, 팔공산까지 아우르는 역사·예술 여행",
      period: "1박 2일",
      time: "상시예약",
      region: "대구",
      place: [
        "대구미술관",
        "김광석 다시그리기길",
        "팔공산 동화사",
        "수성못 카페거리",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 44,
      category: "tour",
      title: "과학과 예술의 융합, 대전 아트 투어",
      theme: [
        "예술",
        "융합"
      ],
      description: "미술·과학·도시문화를 연결한 대전만의 융합형 투어",
      period: "1박 2일",
      time: "상시예약",
      region: "대전",
      place: [
        "대전시립미술관",
        "이응노미술관",
        "성심당",
        "대전 엑스포과학공원",
        "으능정이거리",
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 45,
      category: "tour",
      title: "올림픽공원 속 예술 산책",
      theme: [
        "예술",
        "힐링"
      ],
      description: "공원 속 미술관과 조각공원, 산책이 어우러진 힐링 예술 여행",
      period: "하루",
      time: "상시예약",
      region: "서울시 송파구",
      place: [
        "소마미술관",
        "올림픽공원",
        "석촌호수"
      ],
      price: 10000,
      quantity: 1,
      img: "/images/tour/xx.png"
    },
    {
      id: 46,
      category: "tour",
      title: "손끝의 전통, 공예와 하루",
      theme: [
        "역사",
        "예술",
        "라이프"
      ],
      description: "전통 공예의 아름다움과 북촌·인사동 감성을 느끼는 하루",
      region: "서울 종로구",
      place: [
        "서울공예박물관",
        "북촌 한옥마을",
        "인사동 전통문화거리",
      ],
      period: "하루",
      time: "상시예약",
      price: 30000,
      img: "/images/tour/xx.png",
      quantity: 1
    },
    {
      id: 47,
      category: "tour",
      title: "한옥과 국악, 전통의 하루",
      theme: ["역사", "라이프"],
      description: "한옥마을과 국악 공연, 궁궐 돌담길을 함께 즐기는 도심 전통 산책",
      region: "서울시 종로구",
      place: [
        "돈화문한옥마을",
        "익선동 한옥거리",
      ],
      period: "하루",
      time: "상시예약",
      price: 10000,
      img: "/images/tour/xx.png",
      quantity: 1
    },
    {
      id: 48,
      category: "tour",
      title: "도심 속 전통 한옥 체험",
      theme:["역사","힐링"],
      description: "한복 체험과 한옥·남산타워 전망까지 이어지는 서울 전통 투어",
      region: "서울시 중구",
      place: ["남산골 한옥마을","남산서울타워"],
      period: "하루",
      time: "상시예약",
      price: 10000,
      img: "/images/tour/xx.png",
      quantity: 1
    },
    {
      id: 49,
      category: "tour",
      title: "가야의 시간, 김해 역사여행",
      theme: ["역사"],
      description: "가야문화 유물과 왕릉, 미술관·온천까지 함께하는 역사 여행",
      region: "경상남도 김해시",
      place: ["국립김해박물관",
        "김해 봉하마을",
        "수로왕릉",
        "김해 전통시장",
        "클레이아크김해미술관",
      ],
      period: "1박 2일",
      time: "상시예약",
      price: 10000,
      img: "/images/tour/xx.png",
      quantity: 1
    },
    {
      id: 50,
      category: "tour",
      title: "유네스코 마을, 경주의 숨결",
      theme: ["역사", "힐링"],
      description: "양반마을과 불국사, 보문호수까지 아우르는 경주의 깊은 역사 기행",
      region: "경상북도 경주시",
      place: ["양동마을",
        "월정교",
        "교촌마을",
        "황리단길",
        "불국사",
        "석굴암",
        "경주국립박물관",
        "동궁과 월지",
        "대릉원",
        "첨성대",
      ],
      period: "2박 3일",
      time: "상시예약",
      price: 10000,
      img: "/images/tour/xx.png",
      quantity: 1
    },
    {
      id: 51,
      category: 'class',
      title: '나전칠기 손거울 책갈피 만들기',
      theme: '만들기',
      description: '반짝이는 자개로 전하는 감성 한 조각',
      region: '강원도 원주시',
      place: '원주한지테마파크 1층 열린공간',
      period: '2025.08.22 ~ 10.06',
      time: '120분',
      price: 30000,
      Img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 52,
      category: 'class',
      title: '[열공사포] 액막이 가죽 북어 만들기',
      theme: '만들기',
      description: '복을 부르고 액을 막는 귀여운 한 땀',
      region: '강원도 원주시',
      place: '원주한지테마파크 1층 열린공간',
      period: '2025.09.06 ~ 10.31',
      time: '120분',
      price: 30000,
      Img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 53,
      category: 'class',
      title: '한지, 다도명상을 만나다',
      theme: '체험하기',
      description: '고요한 쉼, 한지와 차에서 찾다',
      region: '강원도 원주시',
      place: '원주한지테마파크 기획전시실1',
      period: '2025.08.01 ~ 10.31',
      time: '90분',
      price: 20000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 54,
      category: 'class',
      title: '화과자, 캐릭터송편만들기',
      theme: '요리하기',
      description: '눈과 입이 모두 즐거운 달콤한 시간',
      region: '경상북도 경주시',
      place: '경주 교촌마을 내 떡인당',
      period: '평일/주말 (수요일 휴무)',
      time: '90분',
      price: 15000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 55,
      category: 'class',
      title: '오곡면 만들기',
      theme: '요리하기',
      description: '곡물의 풍미를 담은 건강한 한 그릇',
      region: '경상북도 경주시',
      place: '경주 교촌마을 내 교촌곳간',
      period: '평일/주말 (화요일,수요일 휴무)',
      time: '40분',
      price: 13000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 56,
      category: 'class',
      title: '직접 만드는 도자기 클래스',
      theme: '체험하기',
      description: '물레 체험, 핸드빌딩, 캐릭터 접시',
      region: '경상북도 경주시',
      place: '경주 교촌마을 내 토기공방/토기가마',
      period: '평일/주말 (수요일 휴무)',
      time: '90분',
      price: 35000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 57,
      category: 'class',
      title: '국궁체험',
      theme: '체험하기',
      description: '전통과 역사 속으로 들어가는 한 발',
      region: '경기도 수원시',
      place: '수원화성 연무대 내 국궁체험장',
      period: '평일/주말 (화요일 휴무)',
      time: '20분',
      price: 3000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 58,
      category: 'class',
      title: '화성어차 타고 도는 수원화성',
      theme: '체험하기',
      description: '왕의 길 위에서 마주하는 수원의 풍경',
      region: '경기도 수원시',
      place: '수원화성 연무대',
      period: '평일/주말 (월요일 휴무)',
      time: '20분',
      price: 6000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 59,
      category: 'class',
      title: '제30회 남한산성문화제 떡메치기 체험',
      theme: '체험하기',
      description: '절구 소리에 담긴 조상의 손맛',
      region: '경기도 광주시',
      place: '남한산성 도립공원 내 전통공원',
      period: '2025.09.19 ~ 10.31',
      time: '60분',
      price: 5000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 60,
      category: 'class',
      title: '제30회 남한산성문화제 선비·다례 체험',
      theme: '체험하기',
      description: '고즈넉한 과거 속 여유를 체험하는 시간',
      region: '경기도 광주시',
      place: '남한산성 도립공원 내 광주문화원/다락원',
      period: '2025.09.19 ~ 10.31',
      time: '40분',
      price: 10000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 61,
      category: 'class',
      title: '민화그리기',
      theme: '체험하기',
      description: '박물관에서 만나는 전통의 결',
      region: '전라북도 전주시',
      place: '국립전주박물관 세미나실',
      period: '평일/주말 (공휴일 휴무)',
      time: '60분',
      price: 15000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 62,
      category: 'class',
      title: '전통쟁반만들기',
      theme: '만들기',
      description: '전통을 담아내는 나만의 쟁반',
      region: '전라북도 전주시',
      place: '국립전주박물관 세미나실',
      period: '평일/주말 (공휴일 휴무)',
      time: '90분',
      price: 25000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 63,
      category: 'class',
      title: '추사그림 따라그리기',
      theme: '체험하기',
      description: '옛 선비의 붓끝을 따라 한 획',
      region: '경기도 과천시',
      place: '과천 추사박물관 체험실',
      period: '평일/주말 (월요일 휴무)',
      time: '20분',
      price: 2000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 64,
      category: 'class',
      title: '서예체험',
      theme: '체험하기',
      description: '먹향 따라 번지는 마음의 여백',
      region: '경기도 과천시',
      place: '과천 추사박물관 체험실',
      period: '평일/주말 (월요일 휴무)',
      time: '50분',
      price: 5000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 65,
      category: 'class',
      title: '2025하회, 선유줄불놀이',
      theme: '체험하기',
      description: '강 위를 수놓는 불의 예술, 하회의 밤',
      region: '경상북도 안동시',
      place: '안동하회마을 낙동강변 일원',
      period: '2025.08.14 ~ 11.08',
      time: '120분',
      price: 10000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 66,
      category: 'class',
      title: '호신팔찌 만들기',
      theme: '만들기',
      description: '한 땀 한 땀 엮어내는 나만의 수호 부적',
      region: '경기도 용인시',
      place: '한국민속촌 내 상설체험장',
      period: '금, 토, 일 및 공휴일',
      time: '60분',
      price: 15000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 67,
      category: 'class',
      title: '금줄놀이',
      theme: '체험하기',
      description: '금지된 장소까지 방울이 울리지 않게 지나가라',
      region: '경기도 용인시',
      place: '한국민속촌 내 상설체험장',
      period: '금, 토, 일 및 공휴일',
      time: '15분',
      price: 5000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 68,
      category: 'class',
      title: '막걸리: 한국 전통주 만들기 클래스',
      theme: '요리하기',
      description: '누룩 향 따라 빚는 나만의 막걸리',
      region: '서울시 강남구',
      place: '시사쿡 컬리너리 아카데미',
      period: '평일 (주말 및 공휴일 휴무)',
      time: '90분',
      price: 50000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 69,
      category: 'class',
      title: '전통 막걸리 양조장 투어 & 시음 체험',
      theme: '체험하기',
      description: '오래된 술의 깊은 맛과 이야기를 만나다',
      region: '서울시 중구',
      place: '스프링 브리즈 양조장',
      period: '매주 목, 금, 토',
      time: '90분',
      price: 30000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 70,
      category: 'class',
      title: '전통 매듭 팔찌 만들기',
      theme: '만들기',
      description: '손끝으로 엮는 아름다운 전통의 매듭',
      region: '서울시 종로구',
      place: '전통 공예관',
      period: '매주 주말 및 공휴일',
      time: '60분',
      price: 20000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 71,
      category: 'class',
      title: '김치 담그기 클래스',
      theme: '요리하기',
      description: '전통 맛 그대로, 김치 담그기 체험',
      region: '전라북도 익산시',
      place: '전통 음식 체험관',
      period: '매주 토, 일',
      time: '90분',
      price: 25000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 72,
      category: 'class',
      title: '전통 한과 만들기',
      theme: '요리하기',
      description: '달콤한 한과를 직접 만들어보는 시간',
      region: '충청남도 공주시',
      place: '한과 공방',
      period: '평일/주말(월요일 휴무)',
      time: '60분',
      price: 30000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 73,
      category: 'class',
      title: '전통 부채 만들기',
      theme: '체험하기',
      description: '전통 미를 담아 직접 만드는 부채',
      region: '서울시 종로구',
      place: '공예 체험관',
      period: '매주 주말 및 공휴일',
      time: '60분',
      price: 15000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 74,
      category: 'class',
      title: '전통 연 만들기',
      theme: '체험하기',
      description: '하늘을 나는 우리 전통 연을 만들어보자',
      region: '경기도 파주시',
      place: '연 공방',
      period: '평일/주말 (화요일 휴무)',
      time: '60분',
      price: 12000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
  {
      id: 75,
      category: 'class',
      title: '전통 장 담그기 체험',
      theme: '체험하기',
      description: '맛과 정성을 담아 우리 장을 만들어보자',
      region: '경기도 이천시',
      place: '장 담그기 체험관',
      period: '매주 일요일',
      time: '120분',
      price: 35000,
      img: '/images/class/xx.png',
      quantity: 1,
  },
    {
      id: 76,
      category: "class",
      title: "한지 서책 만들기",
      theme: "만들기",
      description: "전통 한지를 엮어 만드는 손수 책 체험",
      region: "전라북도 완주군",
      place: "완주 대승한지마을",
      period: "평일/주말 (월요일 휴무)",
      time: "50분",
      price: 8000,
      img: "/images/class/xx.png",
      quantity: 1
     },
       {
      id: 77,
      category: "class",
      title: "한지사 천연염색 에코 스카프",
      theme: "만들기",
      description: "자연의 색을 머금은 한지사로 완성한 친환경 스카프",
      region: "전라북도 완주군",
      place: "완주 대승한지마을",
      period: "평일/주말 (월요일 휴무)",
      time: "70분",
      price: 80000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 78,
      category: "class",
      title: "한지 원형 소품함 만들기",
      theme: "만들기",
      description: "전통 한지로 빚어내는 나만의 원형 소품함 제작",
      region: "전라북도 완주군",
     place: "완주 대승한지마을",
      period: "평일/주말 (월요일 휴무)",
      time: "60분",
      price: 15000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 79,
      category: "class",
      title: "아홉칸의 멋, 구절판 만들기",
      theme: "요리하기",
      description: "아홉 칸에 담긴 전통의 맛과 멋을 직접 완성하는 체험",
      region: "전라북도 전주시",
      place: "전주 한국전통문화전당",
      period: "평일/주말 (화요일 휴무)",
      time: "90분",
      price: 20000,
      img: "/images/class/xx.png",
      quantity: 1
     },
      {
      id: 80,
      category: "class",
      title: "바삭한 전통, 쌀강정 만들기",
      theme: "요리하기",
      description: "고소한 쌀과 달콤한 조청으로 완성하는 우리 전통 간식",
      region: "전라북도 전주시",
      place: "전주 한국전통문화전당",
      period: "평일/주말 (화요일 휴무)",
      time: "60분",
      price: 13000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 81,
      category: "class",
      title: "궁중의 맛, 떡볶이 만들기",
      theme: "요리하기",
      description: "궁중에서 즐기던 간장 양념 떡볶이 체험",
      region: "전라북도 전주시",
      place: "전주 한국전통문화전당",
      period: "평일/주말 (수요일 휴무)",
      time: "60분",
      price: 15000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 82,
      category: "class",
      title: "예와 멋의 길, 전통혼례 체험",
      theme: "체험하기",
      description: "우리 문화유산 속 혼례 예법과 아름다움을 직접 경험하는 시간",
      region: "경상북도 안동시",
      place: "안동하회마을",
      period: "4월~11월, 월요일 휴무",
      time: "90분",
      price: 50000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 83,
      category: "class",
      title: "마음을 새기는 글, 가훈 쓰기 체험",
      theme: "체험하기",
      description: "문서예로 전통의 멋과 가문의 정신을 담아내는 경험",
      region: "경상북도 안동시",
      place: "안동하회마을 內 하중재",
      period: "4월~종료일 까지, 평일 휴무",
      time: "50분",
      price: 15000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 84,
      category: "class",
      title: "손끝에 깃든 전통, 짚공예 체험",
      theme: "체험하기",
      description: "문화유산인 짚으로 생활 소품을 빚어내는 시간",
      region: "경상북도 안동시",
      place: "안동하회마을 內 남촌댁(염행당)",
      period: "4월~종료일 까지, 평일 휴무",
      time: "70분",
      price: 25000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 85,
      category: "class",
      title: "망치로 그려내는 전통금속공예",
      theme: "만들기",
      description: "두드림으로 완성하는 전통의 아름다움",
      region: "서울시 중구",
      place: "남산골한옥마을 옥인동 가옥",
      period: "4월~10월, 매주 금,토,일",
      time: "50분",
      price: 15000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 86,
      category: "class",
      title: "천연자개로 직접 만드는 나만의 공예 작품",
      theme: "만들기",
      description: "자개 빛깔로 완성하는 나만의 전통 작품",
      region: "서울시 중구",
      place: "남산골한옥마을 김춘영 가옥",
      period: "4월~10월, 매주 금,토,일",
      time: "50분",
      price: 25000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 87,
      category: "class",
      title: "2025 남산골 한옥콘서트 <취향>",
      theme: "체험하기",
      description: "한옥의 운치 속에서 즐기는 전통과 현대의 선율",
      region: "서울시 중구",
      place: "남산골한옥마을 관훈동 민씨 가옥",
      period: "9월~11월, 매주 금요일",
      time: "90분",
      price: 30000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 88,
      category: "class",
      title: "옷에 담긴 우리 멋, 한복 체험",
      theme: "체험하기",
      description: "고운 색과 곡선으로 빚어진 전통의 품격을 입어보는 경험",
      region: "서울시 종로구",
      place: "지지배배한복",
      period: "평일/주말 (월요일 휴무)",
      time: "120분",
      price: 30000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 89,
      category: "class",
      title: "다예원, 다도체험",
      theme: "체험하기",
      description: "차 향기 가득한 곳에서 전통 다도를 체험하는 공간.",
      region: "전라남도 장흥군",
      place: "장흥 다예원",
      period: "매주 화, 수요일",
      time: "90분",
      price: 25000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 90,
      category: "class",
      title: "다채로운 도자기 체험",
      theme: "체험하기",
      description: "전통과 예술이 살아 숨 쉬는 공간",
      region: "경기도 이천시",
      place: "사기막골도예촌",
      period: "평일/주말 (월요일 휴무)",
      time: "90분",
      price: 45000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 91,
      category: "class",
      title: "전통 놀이 체험마당",
      theme: "체험하기",
      description: "우리 문화유산 속 놀이를 즐기며 함께 어울리는 시간",
      region: "대전광역시",
      place: "대전 유천동 현장지원센터",
      period: "매주 화요일 오후 2시",
      time: "60분",
      price: 5000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 92,
      category: "class",
      title: "전통주 체험하기",
      theme: "체험하기",
      description: "변하지 않는 전통의 가치, 전통주",
      region: "서울시 종로구",
      place: "한식문화공간 전통주갤러리",
      period: "화요일~일요일, 월요일 휴관",
      time: "60분",
      price: 10000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 93,
      category: "class",
      title: "락고재 컬쳐 라운지 애가헌",
      theme: "체험하기",
      description: "한옥의 품격 속에서 문화와 예술을 함께 즐기는 공간",
      region: "서울시 종로구",
      place: "서울시 종로구 애가헌",
      period: "수요일~일요일",
      time: "150분",
      price: 45000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 94,
      category: "class",
      title: "전통 신 체험",
      theme: "체험하기",
      description: "옛 멋을 담은 전통 신을 직접 신어보는 경험",
      region: "부산광역시 사하구",
      place: "전통신전수관",
      period: "평일/주말 (공휴일 휴무)",
      time: "60",
      price: 50000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 95,
      category: "class",
      title: "수영전통달집놀이",
      theme: "체험하기",
      description: "전통문화 및 전승의 장 체험",
      region: "부산광역시 수영구",
      place: "부산광역시 수영구 광안리해변",
      period: "2월 12일",
      time: "70분",
      price: 2000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 96,
      category: "class",
      title: "안성 남사당놀이 공연",
      theme: "체험하기",
      description: "천년의 흥과 신명이 살아있는 전통 연희를 즐기는 시간",
      region: "경기도 안성시",
      place: "안성 남사당 공연장 ",
      period: "4월~11월, 매주 주말",
      time: "80분",
      price: 12000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 97,
      category: "class",
      title: "진주 무형문화재 공연",
      theme: "체험하기",
      description: "진주성에서 펼쳐지는 국가무형문화재의 흥겨운 무대",
      region: "경상남도 진주시",
      place: "진주성(야외공연장, 촉석루)",
      period: "매주 토요일 오후",
      time: "90분",
      price: 5000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 98,
      category: "class",
      title: "한국전통음식문화체험관",
      theme: "체험하기",
      description: "외국인 친구와 함께가면 더 좋은 평창의 핫플레이스",
      region: "강원도 평창군",
      place: "정강원",
      period: "평일/주말 (매주 월요일, 명절)",
      time: "80분",
      price: 25000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 99,
      category: "class",
      title: "오대산 자연명상마을",
      theme: "체험하기",
      description: "휴식과 치유를 누리는 힐링 한옥 체험",
      region: "강원도 평창군",
      place: "월정사 인근 명상마을",
      period: "평일/주말",
      time: "14시 입실, 11시 퇴실",
      price: 150000,
      img: "/images/class/xx.png",
      quantity: 1
     },
     {
      id: 100,
      category: "class",
      title: "고택문화체험관",
      theme: "체험하기",
      description: "선비문화와 지역적 특색이 공존하는 복합적 문화 관광",
      region: "전라북도 정읍시",
      place: "정읍시 산외면 김동수씨 가옥 옆",
      period: "연중무휴",
      time: "50분",
      price: 10000,
      img: "/images/class/xx.png",
      quantity: 1
     }
]